import test from 'node:test';
import assert from 'node:assert/strict';
import worker from '../worker/worker.js';
import fixture from '../fixtures/known_good_session_day2.json' with { type: 'json' };
import { readFileSync } from 'node:fs';

class MockStmt { constructor(db, sql) { this.db = db; this.sql = sql; this.params = []; } bind(...params) { this.params = params; return this; } async run() { return this.db.run(this.sql, this.params); } async first() { return this.db.first(this.sql, this.params); } async all() { return { results: this.db.all(this.sql, this.params) }; } }
class MockD1 {
  constructor() { this.sessions = new Map(); this.responses = new Map(); this.results = new Map(); this.events = []; this.findings = new Map(); this.evidenceLinks = new Map(); this.followups = new Map(); this.entitlements = new Map(); this.payments = new Map(); this.founders = new Map(); this.ventures = new Map(); }
  prepare(sql) { return new MockStmt(this, sql); }
  async run(sql, p) {
    if (sql.includes('INSERT INTO sessions')) { this.sessions.set(p[0], { session_id:p[0], current_stage:p[1], status:p[2], source:p[3], utm_source:p[4], utm_campaign:p[5], created_at:p[6], updated_at:p[7], last_seen_at:p[8] }); return { success:true }; }
    if (sql.includes('INSERT OR IGNORE INTO founders')) { this.founders.set(p[0], { founder_id:p[0], session_id:p[1], email:p[4] }); return { success:true }; }
    if (sql.includes('INSERT INTO ventures')) { this.ventures.set(p[0], { venture_id:p[0], session_id:p[1], founder_id:p[2], venture_name:p[3] }); return { success:true }; }
    if (sql.includes('INSERT INTO assessment_responses')) { this.responses.set(`${p[1]}:${p[2]}:${p[3]}`, { response_id:p[0], session_id:p[1], product:p[2], question_id:p[3], dimension:p[4], answer_number:p[5], rules_version:p[6] }); return { success:true }; }
    if (sql.includes('INSERT INTO journey_events')) { this.events.push({ event_id:p[0], session_id:p[1], event_name:p[2], product:p[3] }); return { success:true }; }
    if (sql.includes('INSERT INTO product_results')) { if (sql.includes('DO NOTHING') && this.results.has(`${p[1]}:${p[2]}`)) return { success:true }; this.results.set(`${p[1]}:${p[2]}`, { result_id:p[0], session_id:p[1], product:p[2], status:p[3], confidence:p[4], confidence_band:p[5], result_json:p[6], generation_source:p[7], rules_version:p[8], content_version:p[9] }); return { success:true }; }
    if (sql.includes('INSERT INTO clinical_followups')) { this.followups.set(`${p[1]}:${p[3]}:${p[5]}`, { session_id:p[1], product:p[3], question_id:p[5], question_text:p[6], answer:p[7] }); return { success:true }; }
    if (sql.includes('INSERT INTO clinical_findings')) { this.findings.set(`${p[1]}:${p[2]}:${p[3]}`, { session_id:p[1], product:p[2], finding_code:p[3], evidence_ids_json:p[5] }); return { success:true }; }
    if (sql.includes('INSERT INTO galvishot_evidence_links')) { this.evidenceLinks.set(`${p[1]}:${p[2]}:${p[3]}:${p[5]}:${p[8]}`, { evidence_link_id:p[0], session_id:p[1], product:p[2], finding_code:p[3], source_type:p[4], source_field:p[5], display_value:p[6], used_for:p[7], rules_version:p[8], created_at:p[9] }); return { success:true }; }
    throw new Error(`Unhandled SQL run: ${sql}`);
  }
  async first(sql, p) { if (sql.includes('FROM product_results')) return this.results.get(`${p[0]}:${p[1]}`) || null; if (sql.includes('FROM entitlements')) return this.entitlements.get(`${p[0]}:${p[1]}`) || null; if (sql.includes('FROM payments')) return this.payments.get(`${p[0]}:${p[1]}`) || null; if (sql.includes('FROM sessions')) return this.sessions.get(p[0]) || null; throw new Error(`Unhandled SQL first: ${sql}`); }
  all(sql, p) { if (sql.includes('FROM assessment_responses')) return [...this.responses.values()].filter(x => x.session_id === p[0] && x.product === 'GalviTriage').sort((a,b)=>a.question_id.localeCompare(b.question_id)); if (sql.includes('FROM clinical_followups')) return [...this.followups.values()].filter(x => x.session_id === p[0] && x.product === p[1]).sort((a,b)=>a.question_id.localeCompare(b.question_id)); throw new Error(`Unhandled SQL all: ${sql}`); }
}
function req(body) { return new Request('https://worker.test/api', { method:'POST', headers:{ 'Content-Type':'application/json' }, body:JSON.stringify(body) }); }
async function json(response) { return response.json(); }
function env(extra = {}) { return { DB:new MockD1(), D1_FOUNDATION_ENABLED:'true', ENVIRONMENT:'qa', GALVISHOT_QA_OVERRIDE_TOKEN:'qa-ok', ...extra }; }
function payload(session_id, answers) { return { action:'submit_triage', session:{ session_id, source:'test' }, founder:{ ...fixture.founder, consent:true }, venture:{ venture_name:fixture.venture.venture_name, organization_stage:fixture.venture.organization_stage, organization_type:fixture.venture.organization_type, industry:fixture.venture.industry, revenue_range:fixture.venture.revenue_range }, scored_answers:answers }; }
async function seed(e, session_id, overrides = {}) { const answers = { ...fixture.answers, ...overrides }; const res = await worker.fetch(req(payload(session_id, answers)), e); assert.equal(res.status, 200); return answers; }

test('Day 3 locks unpaid GalviShot and omits paid result content', async () => { const e=env(); await seed(e, 'shot_locked', { q07_predictable_revenue:1 }); const res=await worker.fetch(req({ action:'get_or_create_galvishot', session_id:'shot_locked' }), e); const body=await json(res); assert.equal(res.status, 402); assert.equal(body.status, 'locked'); assert.equal(body.result, undefined); });

test('Day 3 QA override is environment scoped and production rejects it', async () => { const e=env({ ENVIRONMENT:'production' }); await seed(e, 'shot_prod', { q07_predictable_revenue:1 }); const res=await worker.fetch(req({ action:'get_or_create_galvishot', session_id:'shot_prod', payload:{ qa_override_token:'qa-ok' } }), e); assert.equal(res.status, 402); });

test('Day 3 creates deterministic stored evidence-linked GalviShot once', async () => { const e=env(); await seed(e, 'shot_revenue', { q07_predictable_revenue:1, q08_revenue_growth_confidence:1, q09_revenue_driver_clarity:1, q04_ideal_customer:1, q10_customer_satisfaction:1 }); let res=await worker.fetch(req({ action:'evaluate_galvishot', session_id:'shot_revenue' }), e); assert.equal((await json(res)).status, 'eligible'); res=await worker.fetch(req({ action:'get_or_create_galvishot', session_id:'shot_revenue', payload:{ qa_override_token:'qa-ok' } }), e); const first=await json(res); assert.equal(first.status, 'ok'); assert.equal(first.result.rules_version, 'galvishot_rules_v0_5_1'); assert.ok(first.result.findings.length >= 3); assert.ok(first.result.findings.every(f => f.evidence.length > 0)); assert.equal(e.DB.results.size, 3); const expectedEvidenceRows = first.result.findings.flatMap(f => f.evidence.map(evidence => ({ finding:f, evidence }))); assert.equal(e.DB.evidenceLinks.size, expectedEvidenceRows.length); for (const { finding, evidence } of expectedEvidenceRows) { const row = e.DB.evidenceLinks.get(`shot_revenue:GalviShot:${finding.finding_code}:${evidence.source_field}:galvishot_rules_v0_5_1`); assert.ok(row); assert.equal(row.product, 'GalviShot'); assert.equal(row.source_type, evidence.source_type); assert.equal(row.display_value, evidence.display_value); assert.equal(row.used_for, evidence.used_for); assert.equal(row.rules_version, 'galvishot_rules_v0_5_1'); assert.equal(row.evidence_link_id, `gshot_ev_${['shot_revenue', finding.finding_code, evidence.source_field, 'galvishot_rules_v0_5_1'].map(value => encodeURIComponent(String(value))).join('__')}`); } const firstEvidenceLinkIds = [...e.DB.evidenceLinks.values()].map(row => row.evidence_link_id).sort(); res=await worker.fetch(req({ action:'get_or_create_galvishot', session_id:'shot_revenue', payload:{ qa_override_token:'qa-ok' } }), e); const second=await json(res); assert.equal(second.stored, true); assert.deepEqual(second.result, first.result); assert.equal(e.DB.results.size, 3); assert.equal(e.DB.evidenceLinks.size, expectedEvidenceRows.length); assert.deepEqual([...e.DB.evidenceLinks.values()].map(row => row.evidence_link_id).sort(), firstEvidenceLinkIds); });

test('Day 3 follow-up save upserts and low-confidence record withholds final result', async () => { const e=env(); await seed(e, 'shot_low'); for (const key of [...e.DB.responses.keys()].filter(k => k.startsWith('shot_low:')).slice(0, 10)) e.DB.responses.delete(key); let res=await worker.fetch(req({ action:'evaluate_galvishot', session_id:'shot_low' }), e); assert.equal((await json(res)).status, 'needs_followup'); await worker.fetch(req({ action:'save_galvishot_followup', session_id:'shot_low', payload:{ answers:[{ question_code:'EVIDENCE_PRIORITY', question_text:'Which evidence signal is strongest?', answer_text:'Customer conversations', confidence_impact:5 }] } }), e); await worker.fetch(req({ action:'save_galvishot_followup', session_id:'shot_low', payload:{ answers:[{ question_code:'EVIDENCE_PRIORITY', question_text:'Which evidence signal is strongest?', answer_text:'Revenue conversion', confidence_impact:5 }] } }), e); assert.equal(e.DB.followups.size, 1); });

test('Day 3 frontend contains no browser finding generator or payment unlock from URL', () => { const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8'); assert.equal(html.includes('function buildResult()'), false); assert.equal(html.includes('localStorage.setItem(GSHOT.PAYMENT_KEY'), false); assert.ok(html.includes('get_or_create_galvishot')); });
