import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import worker from '../worker/worker.js';
import fixture from '../fixtures/known_good_session_day2.json' with { type: 'json' };

class MockStmt{constructor(db,sql){this.db=db;this.sql=sql;this.params=[];}bind(...p){this.params=p;return this;}async run(){return this.db.run(this.sql,this.params);}async first(){return this.db.first(this.sql,this.params);}async all(){return{results:this.db.all(this.sql,this.params)}}}
class MockD1{constructor(){this.sessions=new Map();this.responses=new Map();this.results=new Map();this.events=[];this.findings=new Map();this.evidenceLinks=new Map();this.followups=new Map();this.entitlements=new Map();this.payments=new Map();this.founders=new Map();this.ventures=new Map();}prepare(sql){return new MockStmt(this,sql)}async run(sql,p){if(sql.includes('INSERT INTO sessions')){this.sessions.set(p[0],{session_id:p[0],current_stage:p[1],status:p[2]});return{success:true}}if(sql.includes('INSERT OR IGNORE INTO founders'))return{success:true};if(sql.includes('INSERT INTO ventures'))return{success:true};if(sql.includes('INSERT INTO assessment_responses')){this.responses.set(`${p[1]}:${p[2]}:${p[3]}`,{session_id:p[1],product:p[2],question_id:p[3],dimension:p[4],answer_number:p[5]});return{success:true}}if(sql.includes('INSERT INTO journey_events')){this.events.push({session_id:p[1],event_name:p[2],product:p[3]});return{success:true}}if(sql.includes('INSERT INTO product_results')){if(sql.includes('DO NOTHING')&&this.results.has(`${p[1]}:${p[2]}`))return{success:true};this.results.set(`${p[1]}:${p[2]}`,{result_id:p[0],session_id:p[1],product:p[2],status:p[3],confidence:p[4],confidence_band:p[5],result_json:p[6],generation_source:p[7],rules_version:p[8],content_version:p[9]});return{success:true}}if(sql.includes('INSERT INTO clinical_findings'))return{success:true};if(sql.includes('INSERT INTO galvishot_evidence_links')){this.evidenceLinks.set(`${p[1]}:${p[2]}:${p[3]}:${p[5]}`,{session_id:p[1],product:p[2],finding_code:p[3],source_field:p[5]});return{success:true}}if(sql.includes('INSERT INTO clinical_followups')){this.followups.set(`${p[1]}:${p[3]}:${p[5]}`,{session_id:p[1],product:p[3],question_id:p[5],answer:p[7]});return{success:true}}throw new Error(`Unhandled SQL run: ${sql}`)}async first(sql,p){if(sql.includes('FROM product_results')){const r=this.results.get(`${p[0]}:${p[1]}`);return r&&(!p[2]||r.rules_version===p[2])?r:null}if(sql.includes('FROM entitlements'))return this.entitlements.get(`${p[0]}:${p[1]}`)||null;if(sql.includes('FROM payments'))return this.payments.get(`${p[0]}:${p[1]}`)||null;if(sql.includes('FROM sessions'))return this.sessions.get(p[0])||null;throw new Error(`Unhandled SQL first: ${sql}`)}all(sql,p){if(sql.includes('FROM assessment_responses'))return[...this.responses.values()].filter(x=>x.session_id===p[0]&&x.product==='GalviTriage').sort((a,b)=>a.question_id.localeCompare(b.question_id));if(sql.includes('FROM clinical_followups'))return[...this.followups.values()].filter(x=>x.session_id===p[0]&&x.product===p[1]);throw new Error(`Unhandled SQL all: ${sql}`)}}
function env(extra={}){return{DB:new MockD1(),ENVIRONMENT:'qa',GALVISHOT_QA_OVERRIDE_TOKEN:'qa-ok',...extra}}
function req(body,path='/api'){return new Request(`https://worker.test${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
async function json(r){return r.json()}
function payload(session_id,answers=fixture.answers){return{action:'submit_triage',session:{session_id,source:'test'},founder:{...fixture.founder,email:`${session_id}@example.test`,consent:true},venture:{venture_name:'Synthetic Venture',organization_stage:'QA',organization_type:'LLC',industry:'Services',revenue_range:'Synthetic'},scored_answers:answers}}
async function seedShot(e,sid,overrides={}){await worker.fetch(req(payload(sid,{...fixture.answers,...overrides})),e);let r=await worker.fetch(req({action:'get_or_create_galvishot',session_id:sid,payload:{qa_override_token:'qa-ok'}}),e);assert.equal(r.status,200);return json(r)}

test('Day 4 locks unpaid Sight and Path and production rejects QA override', async()=>{const e=env();await seedShot(e,'d4_lock',{q07_predictable_revenue:1,q08_revenue_growth_confidence:1,q09_revenue_driver_clarity:1});let r=await worker.fetch(req({action:'get_or_generate_galvisight',session_id:'d4_lock'}),e);assert.equal(r.status,402);r=await worker.fetch(req({action:'get_or_generate_galvisight',session_id:'d4_lock',payload:{qa_override_token:'qa-ok'}}),env({DB:e.DB,ENVIRONMENT:'production'}));assert.equal(r.status,402)});

test('Day 4 GalviSight is deterministic, evidence traced, hypothesis-labeled, and idempotent without outbound calls', async()=>{const e=env();await seedShot(e,'d4_sight',{q07_predictable_revenue:1,q08_revenue_growth_confidence:1,q09_revenue_driver_clarity:1,q04_ideal_customer:1});const originalFetch=globalThis.fetch;globalThis.fetch=async()=>{throw new Error('No Day 4 Make/OpenAI/Airtable calls allowed')};try{let r=await worker.fetch(req({action:'get_or_generate_galvisight',session_id:'d4_sight',payload:{qa_override_token:'qa-ok'}}),e);const first=await json(r);assert.equal(r.status,200);assert.equal(first.result.status,'ready');assert.ok(first.result.evidence_trace.length>0);assert.ok(first.result.hypotheses.every(h=>h.label==='Hypothesis'&&h.statement.startsWith('Hypothesis:')));assert.equal(JSON.stringify(first.result).includes('fortune 500'),false);const count=e.DB.results.size;r=await worker.fetch(req({action:'get_or_generate_galvisight',session_id:'d4_sight',payload:{qa_override_token:'qa-ok'}}),e);const second=await json(r);assert.equal(second.stored,true);assert.deepEqual(second.result,first.result);assert.equal(e.DB.results.size,count)}finally{globalThis.fetch=originalFetch}});

test('Day 4 supports low-confidence follow-up and facilitator-review states', async()=>{const e=env();let r; e.DB.results.set('d4_low:GalviShot',{session_id:'d4_low',product:'GalviShot',rules_version:'galvishot_rules_v0_5_1',result_json:JSON.stringify({session_id:'d4_low',product:'GalviShot',status:'ok',confidence:55,findings:[]})});r=await worker.fetch(req({action:'get_or_generate_galvisight',session_id:'d4_low',payload:{qa_override_token:'qa-ok'}}),e);assert.equal((await json(r)).result.status,'needs_followup');e.DB.results.set('d4_review:GalviShot',{session_id:'d4_review',product:'GalviShot',rules_version:'galvishot_rules_v0_5_1',result_json:JSON.stringify({session_id:'d4_review',product:'GalviShot',status:'ok',confidence:90,findings:[{finding_code:'FACILITATOR_REVIEW',title:'Review',evidence:[]}]})});r=await worker.fetch(req({action:'get_or_generate_galvisight',session_id:'d4_review',payload:{qa_override_token:'qa-ok'}}),e);assert.equal((await json(r)).result.status,'facilitator_review')});

test('Day 4 GalviPath returns exactly one pathway with ordered 30/60/90 sequence', async()=>{const e=env();await seedShot(e,'d4_path',{q01_business_clarity:1,q07_predictable_revenue:1,q08_revenue_growth_confidence:1,q09_revenue_driver_clarity:1,q12_organized_operations:1,q17_leadership_confidence:1});await worker.fetch(req({action:'get_or_generate_galvisight',session_id:'d4_path',payload:{qa_override_token:'qa-ok'}}),e);const r=await worker.fetch(req({action:'get_or_generate_galvipath',session_id:'d4_path',payload:{qa_override_token:'qa-ok'}}),e);const body=await json(r);assert.equal(body.result.primary_pathway_count,1);assert.ok(['stabilize','diagnose','validate','build','grow','fundraise','automate','transform'].includes(body.result.primary_pathway));assert.deepEqual(body.result.sequence.map(x=>x.window),['30 days','60 days','90 days']);assert.deepEqual(body.result.sequence.map(x=>x.order),[1,2,3]);assert.ok(body.result.evidence_trace.length>0)});

test('Day 4 preserves legacy root GalviSight route and browser stays renderer-only', async()=>{const calls=[];const old=globalThis.fetch;globalThis.fetch=async(url,init)=>{calls.push({url:String(url),body:JSON.parse(init.body)});return new Response(JSON.stringify({success:true,product:'GalviSight',session_id:'legacy'}),{status:200,headers:{'Content-Type':'application/json'}})};try{const r=await worker.fetch(req({action:'get_or_generate_galvisight',session:{session_id:'legacy'}},'/'),{MAKE_GALVISIGHT_WEBHOOK_URL:'https://make.test/sight'});assert.equal(r.status,200);assert.equal(calls.length,1)}finally{globalThis.fetch=old}const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');for(const forbidden of ['selectPathway(','findingLibrary(','DIMENSION_WEIGHTS','GALVISIGHT_RULES_VERSION'])assert.equal(html.includes(forbidden),false);assert.ok(html.includes('Continue to Chart Your GalviPath'));assert.ok(html.includes('Book GalviClinic'))});
