import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DatabaseSync } from 'node:sqlite';
import worker from '../worker/day4-entry.js';

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=(p)=>fs.readFileSync(path.join(ROOT,p),'utf8');
class Statement{constructor(db,sql,params=[]){this.db=db;this.sql=sql;this.params=params}bind(...p){return new Statement(this.db,this.sql,p)}async first(){return this.db.prepare(this.sql).get(...this.params)??null}async all(){return {success:true,results:this.db.prepare(this.sql).all(...this.params)}}async run(){const r=this.db.prepare(this.sql).run(...this.params);return {success:true,meta:{changes:Number(r.changes),last_row_id:Number(r.lastInsertRowid||0)}}}}
class D1{constructor(db){this.db=db}prepare(sql){return new Statement(this.db,sql)}async batch(stmts){this.db.exec('BEGIN IMMEDIATE');try{const r=[];for(const s of stmts)r.push(await s.run());this.db.exec('COMMIT');return r}catch(e){this.db.exec('ROLLBACK');throw e}}}
function environment(){const sqlite=new DatabaseSync(':memory:');for(const f of ['0001_canonical_business_medical_record.sql','0002_day2_identity_continuity.sql','0003_day3_evidence_versioning.sql','0004_day4_governed_reasoning.sql'])sqlite.exec(read(`migrations/day1/${f}`));return {sqlite,env:{ENVIRONMENT:'qa',FIXTURE_MODE:'true',API_VERSION:'v1',MIN_SCHEMA_VERSION:'0004',ALLOWED_ORIGINS:'https://galvipro.com',DB:new D1(sqlite)}}}
async function call(env,p,{method='GET',body,key,role,actor='qa_test'}={}){const h=new Headers({Origin:'https://galvipro.com','X-Correlation-Id':`corr_${Math.random().toString(16).slice(2)}`});if(body!==undefined)h.set('Content-Type','application/json');if(key)h.set('Idempotency-Key',key);if(role)h.set('X-Galvi-Role',role);if(actor)h.set('X-Galvi-Actor-Id',actor);const r=await worker.fetch(new Request(`https://day4.test${p}`,{method,headers:h,...(body!==undefined?{body:JSON.stringify(body)}:{})}),env);return {r,payload:r.status===204?null:await r.json()}}
async function fixture(){const {sqlite,env}=environment();const s=await call(env,'/api/v1/sessions',{method:'POST',key:'d4-int-session',body:{client_session_key:'d4-int-session',source:'galvivault',current_stage:'GalviTriage',founder:{email:'d4.integration@example.test',first_name:'Day',last_name:'Four',consent_status:'approved'},venture:{venture_name:'D4 Integration Venture',stage:'validation',role_code:'founder',is_primary:true}}});assert.equal(s.r.status,201);const i=s.payload.data.identity;const bmr=i.business_medical_record;const ev=await call(env,'/api/v1/evidence',{method:'POST',key:'d4-int-evidence',body:{bmr_id:bmr.bmr_id,session_id:i.session.session_id,source_type:'assessment_answer',source_ref:'triage.problem_clarity:v1:d4int',value_type:'number',value_number:72,consent_status:'approved',captured_at:new Date().toISOString(),assessment_answer:{question_id:'triage.problem_clarity',question_version:'v1',raw_value_number:72,normalized_value_number:72,confidence_effect:0.2}}});assert.equal(ev.r.status,201);const evidenceId=ev.payload.data.evidence.evidence_id;const accept=await call(env,`/api/v1/evidence/${evidenceId}/accept`,{method:'POST',key:'d4-int-accept',role:'operator',body:{reason:'integration'}});assert.equal(accept.r.status,200);return {sqlite,env,i,bmr,evidenceId}}

test('Day4 readiness proves schema 0004',async()=>{const {env}=environment();const x=await call(env,'/api/v1/day4/readiness');assert.equal(x.r.status,200);assert.equal(x.payload.data.current_schema_version,'0004');assert.equal(x.payload.data.ready,true)});

test('RS-001..006 support lineage and uncertainty execute through cumulative Worker+D1',async()=>{const f=await fixture();const obsBody={bmr_id:f.bmr.bmr_id,statement:'Observed accepted evidence.',domain:'problem',confidence:90,source_type:'deterministic_rule',source_version:'v1',evidence:[{evidence_id:f.evidenceId,support_type:'supports'}]};const badObs=await call(f.env,'/api/v1/observations',{method:'POST',key:'bad-obs',body:{...obsBody,evidence:[]}});assert.equal(badObs.r.status,422);const obs=await call(f.env,'/api/v1/observations',{method:'POST',key:'good-obs',body:obsBody});assert.equal(obs.r.status,201);const obsId=obs.payload.data.observation.observation_id;assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM gv1_observation_evidence WHERE observation_id=?').get(obsId).n,1);const hyp=await call(f.env,'/api/v1/hypotheses',{method:'POST',key:'good-hyp',body:{bmr_id:f.bmr.bmr_id,statement:'Possible explanation.',domain:'problem',confidence:60,uncertainty:'Additional evidence is required.',source_type:'deterministic_rule',source_version:'v1',observations:[{observation_id:obsId,relationship_type:'supports'}]}});assert.equal(hyp.r.status,201);assert.equal(hyp.payload.data.hypothesis.confirmation_status,undefined);const hypId=hyp.payload.data.hypothesis.hypothesis_id;const findingBody={bmr_id:f.bmr.bmr_id,finding_code:'D4_INT',headline:'Integration',statement:'Governed integration finding.',domain:'problem',confidence:80,confirmation_status:'unconfirmed',source_type:'deterministic_rule',source_version:'v1',support:{evidence:[{evidence_id:f.evidenceId,support_type:'supports'}],observations:[{observation_id:obsId,support_type:'supports'}],hypotheses:[{hypothesis_id:hypId,relationship_type:'derived_from'}]}};const bad=await call(f.env,'/api/v1/findings',{method:'POST',key:'bad-find',body:{...findingBody,support:{evidence:[],observations:[],hypotheses:[]}}});assert.equal(bad.r.status,422);const good=await call(f.env,'/api/v1/findings',{method:'POST',key:'good-find',body:findingBody});assert.equal(good.r.status,201);assert.equal(good.payload.data.finding.confirmation_status,'unconfirmed');assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM gv1_finding_evidence WHERE finding_id=?').get(good.payload.data.finding.finding_id).n,1)});

test('IP-004 governance supersession current/history and view boundary are proven in D1',async()=>{const f=await fixture();const obs=await call(f.env,'/api/v1/observations',{method:'POST',key:'r-obs',body:{bmr_id:f.bmr.bmr_id,statement:'Observed evidence.',domain:'problem',confidence:90,source_type:'rule',source_version:'v1',evidence:[{evidence_id:f.evidenceId,support_type:'supports'}]}});const obsId=obs.payload.data.observation.observation_id;const body={bmr_id:f.bmr.bmr_id,finding_code:'D4_REPLAY',headline:'Replay',statement:'Replay governed finding.',domain:'problem',confidence:80,confirmation_status:'unconfirmed',source_type:'rule',source_version:'v1',support:{observations:[{observation_id:obsId,support_type:'supports'}]}};const first=await call(f.env,'/api/v1/findings',{method:'POST',key:'same-find',body});const replay=await call(f.env,'/api/v1/findings',{method:'POST',key:'same-find',body});assert.equal(first.r.status,201);assert.equal(replay.r.status,200);assert.equal(replay.payload.meta.idempotent_replay,true);const id=first.payload.data.finding.finding_id;assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM gv1_findings WHERE finding_id=?').get(id).n,1);const denied=await call(f.env,'/api/v1/governance/confirmations',{method:'POST',key:'deny-confirm',body:{finding_id:id,decision:'confirm',reason:'denied',expected_version:1}});assert.equal(denied.r.status,403);const confirmed=await call(f.env,'/api/v1/governance/confirmations',{method:'POST',key:'ok-confirm',role:'operator',body:{finding_id:id,decision:'confirm',reason:'approved',expected_version:1}});assert.equal(confirmed.payload.data.finding.confirmation_status,'confirmed');const v2=await call(f.env,`/api/v1/findings/${id}/supersede`,{method:'POST',key:'sup-find',role:'operator',body:{expected_version:1,reason:'revision',finding_code:'D4_REPLAY',headline:'Replay v2',statement:'Revised governed finding.',domain:'problem',confidence:85,source_type:'operator_review',source_version:'v2'}});assert.equal(v2.r.status,201);assert.equal(v2.payload.data.finding.version_no,2);assert.equal(v2.payload.data.finding.supersedes_finding_id,id);const history=await call(f.env,`/api/v1/business-medical-records/${f.bmr.bmr_id}/reasoning?history=true`,{role:'operator'});assert.equal(history.payload.data.findings.length,2);const customer=await call(f.env,`/api/v1/business-medical-records/${f.bmr.bmr_id}/customer-projection`);const text=JSON.stringify(customer.payload.data);assert.equal(text.includes('confirmation_reason'),false);assert.equal(text.includes('hypotheses'),false)});

test('LC-004/008/009/010 lifecycle and timeline preserve replay and typed history',async()=>{const f=await fixture();const v1=Number(f.bmr.record_version);const a=await call(f.env,`/api/v1/business-medical-records/${f.bmr.bmr_id}/transitions`,{method:'POST',key:'life-a',role:'operator',body:{to_status:'assessment_in_progress',expected_version:v1,reason_code:'assessment'}});assert.equal(a.r.status,200);const ar=await call(f.env,`/api/v1/business-medical-records/${f.bmr.bmr_id}/transitions`,{method:'POST',key:'life-a',role:'operator',body:{to_status:'assessment_in_progress',expected_version:v1,reason_code:'assessment'}});assert.equal(ar.r.status,200);assert.equal(ar.payload.meta.idempotent_replay,true);const stale=await call(f.env,`/api/v1/business-medical-records/${f.bmr.bmr_id}/transitions`,{method:'POST',key:'life-stale',role:'operator',body:{to_status:'under_review',expected_version:v1,reason_code:'review'}});assert.equal(stale.r.status,409);const u=await call(f.env,`/api/v1/business-medical-records/${f.bmr.bmr_id}/transitions`,{method:'POST',key:'life-u',role:'operator',body:{to_status:'under_review',expected_version:Number(a.payload.data.bmr.record_version),reason_code:'review'}});assert.equal(u.payload.data.bmr.status,'under_review');const timeline=await call(f.env,`/api/v1/business-medical-records/${f.bmr.bmr_id}/timeline`,{role:'operator'});assert.equal(timeline.r.status,200);assert.ok(timeline.payload.data.entries.some(x=>x.entry_type==='session'));assert.ok(timeline.payload.data.entries.some(x=>x.entry_type==='evidence'));assert.ok(timeline.payload.data.entries.some(x=>x.entry_type==='governance'))});
