import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { FOUR_PILLARS, SPUR_TRACKS, SPUR_STAGES, VDM_STAGES, SPRINTS, GALVIPRO_PRACTICE, catalogProjection, findCatalogItem } from '../worker/domain/day6-catalog.js';
const read=p=>readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const migration=read('migrations/day1/0600_day6_studio_vdm.sql');
const service=read('worker/domain/day6-studio-service.js');
const routes=read('worker/routes/day6-studio.js');
const entry=read('worker/day6-entry.js');
const workflow=read('.github/workflows/galvistudio-day6-qa.yml');
const config=JSON.parse(read('wrangler.day6.json'));
const has=(text,items)=>items.every(x=>text.includes(x));

test('T01 branch guard rejects work/main release dependency',()=>assert.ok(has(workflow,["GITHUB_REF_NAME",'qa-revamped-galvicare-0-5','!= "work"','!= "main"'])));
test('T02 signed Day5 ancestry is mandatory',()=>assert.ok(has(workflow,['43cec8bf28dbeeabb6fac340aa5161aa1fc1b94c','merge-base --is-ancestor'])));
test('T03 Day5 gate is inherited',()=>assert.ok(workflow.includes('npm run day5:gate')));
test('T04 Day4 regression is inherited through Day5 gate',()=>assert.ok(workflow.includes('npm run day5:gate')));
test('T05 Day3 regression is inherited through Day5 gate',()=>assert.ok(workflow.includes('npm run day5:gate')));
test('T06 deployment workflow watches Day6 runtime paths',()=>assert.ok(has(workflow,['worker/day6-entry.js','worker/domain/day6-studio-service.js','worker/routes/day6-studio.js','wrangler.day6.json'])));
test('T07 workflow only targets existing QA branch',()=>assert.ok(workflow.includes('branches: [qa-revamped-galvicare-0-5]')&&!workflow.includes('create_branch')));
test('T08 catalog exposes four pillars',()=>assert.deepEqual(FOUR_PILLARS.map(x=>x.code),['founder_development','product_development','business_development','corporate_development']));
test('T09 catalog getter is read-only data projection',()=>assert.equal(catalogProjection().pillars.length,4));
test('T10 SPUR Dreamer exists',()=>assert.ok(SPUR_TRACKS.some(x=>x.code==='dreamer')));
test('T11 principal-only schema permits null BMR',()=>assert.ok(migration.includes('bmr_id TEXT REFERENCES gv1_business_medical_records')));
test('T12 SPUR has three tracks',()=>assert.equal(SPUR_TRACKS.length,3));
test('T13 SPUR has six stages in order',()=>assert.deepEqual(SPUR_STAGES.map(x=>x.code),['Discern','Discover','Prepare','Validate','Build','Steward']));
test('T14 care-prescribed engagement route exists',()=>assert.ok(routes.includes("path==='/api/v1/day6/studio/engagements'")));
test('T15 cross-BMR source plan is denied',()=>assert.ok(service.includes('Source Treatment Plan is outside the authorized BMR.')));
test('T16 prescribing engagement requires physician/operator authority',()=>assert.ok(service.includes('Business Physician or authorized operator scope is required to prescribe a Studio engagement.')));
test('T17 engagement creation is idempotent',()=>assert.ok(has(service,["'day6:studio-engagement'",'GV_IDEMPOTENCY_REUSE_MISMATCH'])));
test('T18 engagement stores catalog/sprint versions',()=>assert.ok(has(migration,['catalog_version TEXT NOT NULL','sprint_version TEXT'])));
test('T19 principal-only engagement does not require BMR',()=>assert.ok(service.includes("if(!bmrId)return{principal,bmr:null")));
test('T20 ADVANCE requires evidence',()=>assert.ok(service.includes("decision==='ADVANCE'&&(!required.length||missing.length)")));
test('T21 HOLD is first-class',()=>assert.ok(service.includes("['ADVANCE','HOLD','REWORK','STOP']")));
test('T22 REWORK is append-only stage decision',()=>assert.ok(migration.includes("decision TEXT NOT NULL CHECK (decision IN ('ADVANCE','HOLD','REWORK','STOP'))")));
test('T23 STOP closes without deletion',()=>assert.ok(service.includes("decision==='STOP'?'closed'")&&!service.includes('DELETE FROM gv1_studio')));
test('T24 stage skipping is rejected',()=>assert.ok(service.includes('Stage skipping is prohibited')));
test('T25 customer/Guide lack stage-gate authority',()=>assert.ok(service.includes("STUDIO_DECISION_ROLES=new Set(['business_physician','studio_operator','operator','admin'])")));
test('T26 stage decision stores actor/version/audit',()=>assert.ok(has(migration,['decision_actor_type','decision_actor_id','version_no','correlation_id'])));
test('T27 capital exposure cannot become autonomous decision',()=>assert.ok(service.includes('rejectRegulated(input.intervention,input.capital_exposure)')));
test('T28 Founder Readiness Sprint exists',()=>assert.ok(SPRINTS.some(x=>x.code==='founder_readiness_sprint')));
test('T29 Venture Validation Sprint exists',()=>assert.ok(SPRINTS.some(x=>x.code==='venture_validation_sprint')));
test('T30 Product Readiness Sprint exists',()=>assert.ok(SPRINTS.some(x=>x.code==='product_readiness_sprint')));
test('T31 GTM Readiness Sprint exists',()=>assert.ok(SPRINTS.some(x=>x.code==='gtm_readiness_sprint')));
test('T32 Revenue/Growth Recovery Sprint exists',()=>assert.ok(SPRINTS.some(x=>x.code==='revenue_growth_recovery_sprint')));
test('T33 Operational Readiness Sprint exists',()=>assert.ok(SPRINTS.some(x=>x.code==='operational_readiness_sprint')));
test('T34 Fundraising/Capital Sprint preserves regulated boundary',()=>assert.ok(SPRINTS.find(x=>x.code==='fundraising_capital_readiness_sprint')?.regulated_boundary));
test('T35 artifact references reuse evidence IDs rather than shadow documents',()=>assert.ok(has(migration,['gv1_studio_artifact_refs','evidence_id TEXT'])));
test('T36 outcome requires evidence refs',()=>assert.ok(service.includes("Studio outcome requires evidence_refs.")));
test('T37 outcome write is idempotent',()=>assert.ok(service.includes("'day6:outcome'")));
test('T38 Day6 migration is additive',()=>{assert.equal(migration.includes('DROP TABLE'),false);assert.equal(migration.includes('DELETE FROM'),false)});
test('T39 outcome creates explicit reassessment',()=>assert.ok(has(service,['gv1_reassessments','Studio outcome recorded; Business Physician reassessment is required.'])));
test('T40 Day6 wraps rather than replaces Day5 runtime',()=>assert.ok(entry.includes("import day5Worker from './day5-entry.js'")));
test('T41 protected projection uses explicit Day6 endpoint, not canonical overwrite',()=>assert.ok(routes.includes('/api/v1/day6/studio/engagements/')&&!service.includes('UPDATE gv1_business_medical_records SET')));
test('T42 cross-record Studio access fails closed',()=>assert.ok(service.includes('Cross-record Studio access is prohibited.')));
test('T43 GalviGuide is bounded away from treatment/stage authority',()=>assert.ok(!GALVIPRO_PRACTICE.galviguide.join(' ').includes('treatment approval')&&!service.includes("'galviguide','studio_operator'")));
test('T44 GalviGage requires treatment order/scope/evidence/duration/follow-up',()=>assert.ok(has(service,['GV_GAGE_ORDER_REQUIRED',"['scope','objective','duration_pattern','follow_up']",'GalviGage requires required_evidence.'])));
test('T45 regulated work fails closed to referral',()=>assert.ok(has(service,['GV_STUDIO_REFERRAL_REQUIRED','referral_required'])));
test('T46 Venture 001 validated proof requires evidence',()=>assert.ok(service.includes('GV_PROOF_EVIDENCE_REQUIRED')));
test('T47 unsupported proof remains unsupported',()=>assert.ok(service.includes("refs.length?requested||'draft':'unsupported'")));
test('T48 Day5 Stripe/Calendly runtime remains inherited',()=>assert.ok(entry.includes('day5Worker.fetch')&&config.vars.GALVICLINIC_BOOKING_URL));
test('T49 Day6 errors stay structured through Day5 failure envelope',()=>assert.ok(entry.includes('failure(ctx,error)')));
test('T50 full Day6 contract is cumulative and QA-only',()=>{assert.equal(config.name,'galvivault-p0-day1-qa');assert.equal(config.main,'worker/day6-entry.js');assert.equal(config.vars.ENVIRONMENT,'qa');assert.equal(config.d1_databases[0].database_id,'cdf9042b-ab09-498a-ac66-010b6cce47d4');assert.ok(findCatalogItem('gtm_readiness'));assert.equal(VDM_STAGES[0],'Discover')});
