import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const read=(p)=>fs.readFileSync(p,'utf8');
const req=JSON.parse(read('release-evidence/day7/day7-release-requirements.json'));

test('Day 7 release requirements enumerate exact mandatory matrices',()=>{
  assert.equal(req.manual_repair,false);
  assert.deepEqual(req.t01_t60.map(x=>x.id),Array.from({length:60},(_,i)=>`T${String(i+1).padStart(2,'0')}`));
  assert.deepEqual(req.d1.map(x=>x.id),Array.from({length:22},(_,i)=>`D1-${i+1}`));
  assert.deepEqual(req.golden_cases.map(x=>x.id),['A','B','C','D','E','F','G','H','I']);
  assert.deepEqual(req.human_e2e.map(x=>x.id),Array.from({length:16},(_,i)=>`P0-${String(i+1).padStart(2,'0')}`));
  assert.deepEqual(req.release_gates,['GalviCare 1.0','GalviStudio 1.0','GalviPro 1.0']);
  assert.equal(req.evidence_sections.length,14);
  assert.equal(req.go_rule,'FAIL_CLOSED_UNTIL_ALL_MANDATORY_GREEN');
});
for(const item of req.t01_t60){test(`${item.id} release control is explicit and evidence-bound`,()=>{assert.ok(item.assertion.length>=30,`${item.id} assertion too weak`);assert.ok(['automated_or_contract','hybrid','human_or_hybrid'].includes(item.evidence_mode));});}

test('Day 7 membership migration is additive and preserves canonical record authority',()=>{const sql=read('migrations/day1/0700_day7_release_membership.sql');for(const table of ['gv1_memberships','gv1_membership_events','gv1_membership_checkins','gv1_membership_reassessment_queue','gv1_customer_accounts','gv1_customer_login_invites','gv1_customer_login_sessions'])assert.match(sql,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));assert.match(sql,/D7A1/);assert.match(sql,/ux_gv1_memberships_one_active_bmr/);assert.doesNotMatch(sql,/\b(DROP|DELETE FROM|TRUNCATE)\b/i);});

test('D7A2 commercial return and FounderShot migration remains immutable and additive',()=>{const sql=read('migrations/day1/0710_day7_commercial_return_foundershot.sql');for(const table of ['gv1_commercial_care_orders','gv1_systeme_integration_events','gv1_care_reassessment_queue','gv1_founder_snapshots','gv1_lifecycle_transition_reviews'])assert.match(sql,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));assert.match(sql,/D7A2/);assert.doesNotMatch(sql,/\b(DROP|DELETE FROM|ALTER TABLE|TRUNCATE)\b/i);});

test('D7A3 preserves Stripe payment authority and coarse Systeme delivery compatibility',()=>{const sql=read('migrations/day1/0720_day7_stripe_systeme_treatment_delivery.sql');for(const marker of ['D7A3','gv1_commercial_order_delivery','payment_provider','stripe_checkout_session_id','payment_status','payment_verified_at','fulfillment_provider','systeme_course_id','enrollment_status','gv1_treatment_payment_events','ux_gv1_commercial_delivery_stripe_checkout'])assert.match(sql,new RegExp(marker));assert.match(sql,/DEFAULT 'stripe'/);assert.match(sql,/DEFAULT 'systeme'/);assert.doesNotMatch(sql,/\b(DROP|DELETE FROM|ALTER TABLE|TRUNCATE)\b/i);});

test('D7A4 adds one GalviVault Systeme fulfillment per prescribed Sprint without destructive migration',()=>{const sql=read('migrations/day1/0730_day7_multi_sprint_systeme_fulfillment.sql');for(const marker of ['D7A4','gv1_systeme_course_fulfillments','completion_key','systeme_course_id','systeme_contact_id','systeme_enrollment_id','access_type','enrollment_status','completion_status','attempt_count','UNIQUE\(order_id, completion_key\)'])assert.match(sql,new RegExp(marker));assert.match(sql,/full_access/);assert.doesNotMatch(sql,/\b(DROP|DELETE FROM|ALTER TABLE|TRUNCATE)\b/i);});

test('Day 7 runtime remains additive: commercial wrapper -> customer access -> signed Day 7 -> signed Day 6 runtime',()=>{const commercial=read('worker/day7-commercial-entry.js'),access=read('worker/day7-customer-entry.js'),entry=read('worker/day7-entry.js');assert.match(commercial,/import day7CustomerWorker from '.\/day7-customer-entry\.js'/);assert.match(commercial,/day7CustomerWorker\.fetch/);assert.match(access,/import day7Worker from '.\/day7-entry\.js'/);assert.match(access,/day7Worker\.fetch/);assert.match(entry,/import day6Worker from '.\/day6-entry\.js'/);assert.match(entry,/handleDay7ReleaseRoute/);assert.match(entry,/day6Worker\.fetch/);assert.match(entry,/X-Galvi-Day7-Release/);});

test('Pre-Founder governed-AI refresh reuses the canonical generation instead of creating a duplicate attempt',()=>{const entry=read('worker/day7-entry.js');for(const re of [/storedPreFounderAiReplay/,/PREFOUNDER_AI_PATH='\/api\/v1\/day7\/prefounder\/readiness-interpretation'/,/gv1_prefounder_sessions/,/gv1_day2_intake_results/,/gv1_day3_ai_generations/,/request_fingerprint=\? AND attempt_no=1/,/canonical_generation_reuse:true/,/gv1_idempotency_keys/,/GV_IDEMPOTENCY_REUSE_MISMATCH/])assert.match(entry,re);assert.match(entry,/const stored=await storedPreFounderAiReplay\(request,env,ctx,path\)/);assert.match(entry,/const recovered=await storedPreFounderAiReplay\(request,env,ctx,path\)/);});

test('Operating-Founder score mismatch converges by versioned canonical projection and keeps fail-closed guard',()=>{const entry=read('worker/day7-entry.js');for(const re of [/OPERATING_BOOTSTRAP_PATH='\/api\/v1\/day3\/customer-bootstrap'/,/GV_DAY3_CUSTOMER_SCORE_MISMATCH/,/clinicalFile/,/day7_p1_authoritative_galviscore/,/gv1_day2_intake_results/,/record_version/,/manual_repair:'NO'/,/X-Galvi-Day7-P1-Score-Convergence/])assert.match(entry,re);assert.doesNotMatch(entry,/UPDATE\s+gv1_day2_intake_results|DELETE\s+FROM\s+gv1_day2_intake_results|DROP\s+TABLE/i);});

test('Phase B QA presentation preserves stored picklist values and aligns urgency copy to server-owned Acuity',()=>{const worker=read('qa-frontend-worker.js');assert.match(worker,/Consulting \/ Coaching \/ Creative Entrepreneur/);assert.match(worker,/NFP \/ Academic Institution/);assert.match(worker,/day5-acuity-badge/);assert.match(worker,/Routine care — no urgent escalation identified/);assert.match(worker,/Needs attention — passive intervention/);assert.match(worker,/Material concern — active care recommended/);assert.match(worker,/Urgent — prompt active \/ specialty care/);assert.doesNotMatch(worker,/acuity.*0\.30|severity.*0\.30|Business Health.*acuity.*score/i);});

test('Business Health Membership is treatment-plan bound and closes clinical decision to commercial offer to paid activation',()=>{const svc=read('worker/domain/day7-membership-service.js'),entry=read('worker/day7-entry.js'),clinician=read('worker/day8-day6-entry.js'),customer=read('day5-customer-care-routing.js');for(const marker of ['recommendMembership','membership_recommended','membership_offered','resolvePaidMembershipActivation','membership_paid_activation','STRIPE_SECRET_KEY','payment_status','client_reference_id','MEMBERSHIP_PRODUCT_ALIASES','membership_started','revenue_conversion_event'])assert.ok(svc.includes(marker),marker);assert.match(svc,/Cross-BMR membership treatment scope is prohibited/);assert.match(svc,/gv1_membership_reassessment_queue/);assert.match(svc,/submitCheckin/);assert.match(entry,/\/api\/v1\/day7\/customer\/membership-offer/);assert.match(entry,/\/api\/v1\/day7\/customer\/membership-payment-return/);assert.match(entry,/revenue_conversion:true/);assert.match(clinician,/commercial_event:'membership_recommended'/);assert.match(customer,/Your Business Physician recommends Continuous Care/);assert.match(customer,/client_reference_id/);assert.match(customer,/membership-payment-return/);assert.match(customer,/Clinical decision and purchase are separate/);assert.doesNotMatch(customer,/STRIPE_SECRET_KEY|Authorization:`Bearer/);});

test('Returning customer login restores canonical access without browser-owned authority',()=>{const svc=read('worker/domain/day7-customer-access-service.js'),entry=read('worker/day7-customer-entry.js'),ui=read('qa-frontend-worker.js');for(const marker of ['PBKDF2','SHA-256','membership_recommended','active_membership','membership_reassessment','legacy_session_id','GalviShot'])assert.ok(svc.includes(marker),marker);assert.match(entry,/customer-access\/login/);assert.match(entry,/customer-access\/activate/);assert.match(ui,/Returning Patient\? Log in to GalviCare/);assert.match(ui,/GalviChartDay4\.open/);assert.doesNotMatch(ui,/password_hash|password_salt|HUBSPOT_PRIVATE_APP_TOKEN/);});

test('Provider-verified completion cannot skip payment, enrollment, or customer completion confirmation',()=>{const svc=read('worker/domain/day7-commercial-care-service.js'),entry=read('worker/day7-commercial-entry.js'),fulfillment=read('worker/domain/day7-systeme-fulfillment-completion-service.js'),browser=read('day7-commercial-browser.js');for(const marker of ['gv1_commercial_care_orders','gv1_systeme_integration_events','provider_verified_treatment_completion','GV_TREATMENT_COMPLETION_REQUIRED','GV_PROVIDER_COMPLETION_REQUIRED','SYSTEME_WEBHOOK_TOKEN','course_completed','customer_confirmed'])assert.ok(svc.includes(marker),marker);assert.match(entry,/\/api\/v1\/integrations\/systeme/);assert.match(entry,/recordSystemeFulfillmentCompletion/);assert.match(entry,/requireTreatmentCompletionBeforeMonitoring/);assert.match(fulfillment,/gv1_systeme_course_fulfillments/);assert.match(fulfillment,/GV_SYSTEME_ENROLLMENT_REQUIRED/);assert.match(fulfillment,/GV_SYSTEME_COURSE_MISMATCH/);assert.match(browser,/Record Verified Treatment Completion in GalviCare/);assert.match(browser,/Business Physician reassessment queued/);assert.doesNotMatch(browser,/SYSTEME_WEBHOOK_TOKEN|OPENAI_API_KEY|api\.openai\.com/);});

test('D7A4 treatment commerce uses Stripe TEST then direct Worker-to-Systeme Public API enrollment',()=>{const svc=read('worker/domain/day7-stripe-systeme-service.js'),entry=read('worker/day7-commercial-entry.js'),browser=read('day7-commercial-browser.js');for(const marker of ['STRIPE_SECRET_KEY','STRIPE_TREATMENT_WEBHOOK_SECRET','Stripe-Signature','checkout.session.completed','galvicare_order_id','payment_status','SYSTEME_API_KEY','SYSTEME_API','gv1_systeme_course_fulfillments','requestSystemeEnrollments','requiredCourseConfig','/school/courses/','full_access'])assert.ok(svc.includes(marker),marker);assert.match(svc,/QA treatment checkout requires a Stripe TEST secret/);assert.match(svc,/payment_status='paid'/);assert.match(svc,/SYSTEME_API='https:\/\/api\.systeme\.io\/api'/);assert.doesNotMatch(svc,/env\.SYSTEME_ENROLLMENT_ADAPTER_URL/);assert.match(entry,/\/api\/v1\/integrations\/stripe\/treatment/);assert.doesNotMatch(entry,/\(sale\|course-completed\|sale-canceled\)/);assert.match(browser,/Stripe TEST Checkout/);assert.match(browser,/browser return alone does not authorize treatment/);assert.match(browser,/Systeme\.io treatment enrollment active/);assert.doesNotMatch(browser,/STRIPE_SECRET_KEY|STRIPE_TREATMENT_WEBHOOK_SECRET|SYSTEME_API_KEY/);});

test('Option B compound Treatment Plans preserve one order while creating one fulfillment per completion key',()=>{const svc=read('worker/domain/day7-stripe-systeme-service.js'),catalog=read('worker/domain/day7-commercial-care-service.js');assert.match(catalog,/venture_builder_plan/);assert.match(catalog,/founder_readiness_sprint','venture_readiness_sprint','product_readiness_sprint/);assert.match(svc,/required=item\.completion/);assert.match(svc,/courseConfig\.map\(x=>fulfillmentInsert/);assert.match(svc,/UNIQUE|completion_key/);assert.match(svc,/treatment_plan_orchestrator:'galvivault'/);});

test('Stripe treatment webhook is replay safe and browser return is not entitlement authority',()=>{const sql=read('migrations/day1/0720_day7_stripe_systeme_treatment_delivery.sql'),svc=read('worker/domain/day7-stripe-systeme-service.js'),browser=read('day7-commercial-browser.js');assert.match(sql,/provider_event_key TEXT NOT NULL UNIQUE/);assert.match(svc,/WHERE provider_event_key=\?/);assert.match(svc,/idempotent_replay:true/);assert.match(svc,/Math\.abs\(Date\.now\(\)\/1000-epoch\)>300/);assert.match(browser,/waiting for the server-verified Stripe payment event/i);});

test('FounderShot is evidence-bound, visible for principal/BMR contexts, and lifecycle changes require Business Physician confirmation',()=>{const svc=read('worker/domain/day7-commercial-care-service.js'),life=read('worker/domain/day7-lifecycle-service.js'),clinician=read('worker/day8-commercial-entry.js');for(const marker of ['FOUNDER_SHOT_PROMPT','founder_snapshot','lifecycle_assessment','supporting_evidence_refs','A venture name or founder title alone is NOT evidence','openai_governed'])assert.ok(svc.includes(marker),marker);assert.match(life,/Business Physician authority is required/);assert.match(life,/principal_only/);assert.match(life,/principal_plus_venture/);assert.match(life,/graduated_to_business_health/);assert.match(clinician,/proposal_not_transition/);assert.match(clinician,/canonical_transition:'business_physician_confirmed'/);});

test('Day 7 QA config reuses exact QA Worker and canonical QA D1 with D7A4 additive wrapper',()=>{const w=JSON.parse(read('wrangler.day7.json')),db=w.d1_databases?.[0];assert.equal(w.name,'galvivault-p0-day1-qa');assert.equal(w.main,'worker/day7-commercial-entry.js');assert.equal(w.vars?.ENVIRONMENT,'qa');assert.equal(w.vars?.MIN_SCHEMA_VERSION,'D7A1');assert.equal(w.vars?.DAY7_BUSINESS_HEALTH_MEMBERSHIP,'server_governed_beta_v1');assert.equal(w.vars?.DAY7_CUSTOMER_ACCESS,'business_physician_queue_only_v1');assert.equal(w.vars?.DAY7_COMMERCIAL_SCHEMA,'D7A4');assert.equal(w.vars?.DAY7_COMMERCIAL_PAYMENT_AUTHORITY,'stripe_test_v1');assert.equal(w.vars?.DAY7_TREATMENT_FULFILLMENT_AUTHORITY,'systeme_public_api_v1');assert.equal(w.vars?.DAY7_TREATMENT_PLAN_ORCHESTRATOR,'galvivault_multi_sprint_v1');assert.equal(w.vars?.DAY7_COMMERCIAL_RETURN,'stripe_payment_systeme_completion_v3');assert.equal(w.vars?.DAY7_FOUNDER_SHOT,'governed_founder_mri_v1');assert.equal(db?.binding,'DB');assert.equal(db?.database_name,'galvivault-0-5-qa');assert.equal(db?.database_id,'cdf9042b-ab09-498a-ac66-010b6cce47d4');});

test('Human E2E and release evidence remain fail-closed rather than auto-passed',()=>{const runbook=read('release-evidence/day7/day7-human-e2e-runbook.md');for(const id of req.human_e2e.map(x=>x.id))assert.match(runbook,new RegExp(id));for(const id of req.golden_cases.map(x=>`Golden ${x.id}`))assert.match(runbook,new RegExp(id));assert.match(runbook,/manual_repair=NO/);assert.match(runbook,/Do not promote `main`/i);});
