import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const read=(p)=>fs.readFileSync(p,'utf8');
const req=JSON.parse(read('release-evidence/day7/day7-release-requirements.json'));

test('Day 7 release requirements enumerate exact mandatory matrices',()=>{
  assert.equal(req.manual_repair,false);
  assert.deepEqual(req.t01_t60.map(x=>x.id),Array.from({length:60},(_,i)=>`T${String(i+1).padStart(2,'0')}`));
  assert.deepEqual(req.d1.map(x=>x.id),Array.from({length:22},(_,i)=>`D1-${i+1}`));
  assert.deepEqual(req.golden_cases.map(x=>x.id),['A','B','C','D','E','F','G','H','I']);
  assert.deepEqual(req.human_e2e.map(x=>x.id),Array.from({length:16},(_,i)=>`P0-${String(i+1).padStart(2,'0')}`));
  assert.deepEqual(req.release_gates,['GalviCare 1.0','GalviStudio 1.0','GalviPro 1.0']);
  assert.equal(req.evidence_sections.length,14);
  assert.equal(req.go_rule,'FAIL_CLOSED_UNTIL_ALL_MANDATORY_GREEN');
});
for(const item of req.t01_t60){test(`${item.id} release control is explicit and evidence-bound`,()=>{assert.ok(item.assertion.length>=30,`${item.id} assertion too weak`);assert.ok(['automated_or_contract','hybrid','human_or_hybrid'].includes(item.evidence_mode));});}
test('Day 7 membership migration is additive and preserves canonical record authority',()=>{const sql=read('migrations/day1/0700_day7_release_membership.sql');for(const table of ['gv1_memberships','gv1_membership_events','gv1_membership_checkins','gv1_membership_reassessment_queue']) assert.match(sql,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));assert.match(sql,/D7A1/);assert.match(sql,/ux_gv1_memberships_one_active_bmr/);assert.doesNotMatch(sql,/\b(DROP|DELETE FROM|ALTER TABLE|TRUNCATE)\b/i);});
test('Day 7 runtime is an additive wrapper over the signed Day 6 runtime',()=>{const entry=read('worker/day7-entry.js');assert.match(entry,/import day6Worker from '.\/day6-entry\.js'/);assert.match(entry,/handleDay7ReleaseRoute/);assert.match(entry,/day6Worker\.fetch/);assert.match(entry,/X-Galvi-Day7-Release/);});
test('Pre-Founder governed-AI refresh reuses the canonical generation instead of creating a duplicate attempt',()=>{const entry=read('worker/day7-entry.js');for(const re of [/storedPreFounderAiReplay/,/PREFOUNDER_AI_PATH='\/api\/v1\/day7\/prefounder\/readiness-interpretation'/,/gv1_prefounder_sessions/,/gv1_day2_intake_results/,/gv1_day3_ai_generations/,/request_fingerprint=\? AND attempt_no=1/,/canonical_generation_reuse:true/,/gv1_idempotency_keys/,/GV_IDEMPOTENCY_REUSE_MISMATCH/])assert.match(entry,re);assert.match(entry,/const stored=await storedPreFounderAiReplay\(request,env,ctx,path\)/);assert.match(entry,/const recovered=await storedPreFounderAiReplay\(request,env,ctx,path\)/);});
test('Operating-Founder score mismatch converges by versioned canonical projection and keeps fail-closed guard',()=>{const entry=read('worker/day7-entry.js');for(const re of [/OPERATING_BOOTSTRAP_PATH='\/api\/v1\/day3\/customer-bootstrap'/,/GV_DAY3_CUSTOMER_SCORE_MISMATCH/,/clinicalFile/,/day7_p1_authoritative_galviscore/,/gv1_day2_intake_results/,/record_version/,/manual_repair:'NO'/,/X-Galvi-Day7-P1-Score-Convergence/])assert.match(entry,re);assert.doesNotMatch(entry,/UPDATE\s+gv1_day2_intake_results|DELETE\s+FROM\s+gv1_day2_intake_results|DROP\s+TABLE/i);});
test('Phase B QA presentation preserves stored picklist values and aligns urgency copy to server-owned Acuity',()=>{const worker=read('qa-frontend-worker.js');assert.match(worker,/Consulting \/ Coaching \/ Creative Entrepreneur/);assert.match(worker,/NFP \/ Academic Institution/);assert.match(worker,/day5-acuity-badge/);assert.match(worker,/Routine care — no urgent escalation identified/);assert.match(worker,/Needs attention — passive intervention/);assert.match(worker,/Material concern — active care recommended/);assert.match(worker,/Urgent — prompt active \/ specialty care/);assert.doesNotMatch(worker,/acuity.*0\.30|severity.*0\.30|Business Health.*acuity.*score/i);});
test('Business Health Membership is treatment-plan bound and closes clinical decision to commercial offer to paid activation',()=>{const svc=read('worker/domain/day7-membership-service.js'),entry=read('worker/day7-entry.js'),clinician=read('worker/day8-day6-entry.js'),customer=read('day5-customer-care-routing.js');for(const marker of ['recommendMembership','membership_recommended','membership_offered','resolvePaidMembershipActivation','membership_paid_activation','STRIPE_SECRET_KEY','payment_status','client_reference_id','MEMBERSHIP_PRODUCT_ALIASES','membership_started','revenue_conversion_event'])assert.ok(svc.includes(marker),marker);assert.match(svc,/Cross-BMR membership treatment scope is prohibited/);assert.match(svc,/gv1_membership_reassessment_queue/);assert.match(svc,/submitCheckin/);assert.match(entry,/\/api\/v1\/day7\/customer\/membership-offer/);assert.match(entry,/\/api\/v1\/day7\/customer\/membership-payment-return/);assert.match(entry,/revenue_conversion:true/);assert.match(clinician,/commercial_event:'membership_recommended'/);assert.match(customer,/Your Business Physician recommends Continuous Care/);assert.match(customer,/client_reference_id/);assert.match(customer,/membership-payment-return/);assert.match(customer,/Clinical decision and purchase are separate/);assert.doesNotMatch(customer,/STRIPE_SECRET_KEY|Authorization:`Bearer/);});
test('Membership clinician surface recommends care and never starts or charges the customer',()=>{const ui=read('clinician-portal/day7-membership.js');assert.match(ui,/Recommend Business Health Membership/);assert.match(ui,/membership\/recommend/);assert.match(ui,/customer—not the clinician—accepts the commercial offer/);assert.match(ui,/Membership becomes active only after server-verified paid activation/);assert.doesNotMatch(ui,/Start Business Health Membership/);assert.doesNotMatch(ui,/STRIPE_SECRET_KEY|api\.stripe\.com/);});
test('Pre-Founder AI projection is server-side, evidence-bound, replay-safe and cannot overwrite Founder Readiness',()=>{const route=read('worker/routes/day7-release.js'),customer=read('day1-prefounder-customer.js');for(const re of [/\/api\/v1\/day7\/prefounder\/readiness-interpretation/,/deterministic_truth_immutable:true/,/record_mode!=='principal_only'/,/venture_id!==null\|\|row\.bmr_id!==null/,/gv1_audit_log/,/gv1_idempotency_keys/,/gv1_day3_ai_generations/,/gv1_day3_generation_evidence/,/evidence_bundle_hash/,/deterministic_context_hash/,/text:\{format:\{type:'json_schema'/,/generationSource='openai_governed'/,/rules_fallback/,/validationStatus='rejected'/,/canonical_generation_ledger:true/,/production_synthetic_route:false/]) assert.match(route,re);assert.doesNotMatch(customer,/api\.openai\.com|OPENAI_API_KEY|sk-[A-Za-z0-9_-]{16,}/);});
test('Deployed Day 7 E2E fail-closes on real P0-06 governed AI and canonical generation ledger',()=>{const deployed=read('scripts/day7-deployed-release-e2e.mjs');for(const contract of ['P0-06-openai-governed-projection','P0-06-idempotent-replay','D1-2-prefounder-principal-only','D1-5-prefounder-ai-generation-ledger','D1-5-prefounder-ai-evidence-links','D1-16-prefounder-ai-audit','D1-7-prefounder-ai-replay-safe','P0-06-canonical-score-immutable','D1-22-manual-repair-no']) assert.match(deployed,new RegExp(contract));assert.match(deployed,/X-Galvi-Day1-Actor/);assert.match(deployed,/generation_source==='openai_governed'/);assert.match(deployed,/validation_status==='accepted'/);assert.match(deployed,/gv1_day3_ai_generations/);assert.match(deployed,/gv1_day3_generation_evidence/);});
test('Day 7 QA config reuses exact QA Worker and canonical QA D1 with D7 additive schema',()=>{const w=JSON.parse(read('wrangler.day7.json')),db=w.d1_databases?.[0];assert.equal(w.name,'galvivault-p0-day1-qa');assert.equal(w.main,'worker/day7-entry.js');assert.equal(w.vars?.ENVIRONMENT,'qa');assert.equal(w.vars?.MIN_SCHEMA_VERSION,'D7A1');assert.equal(w.vars?.DAY7_BUSINESS_HEALTH_MEMBERSHIP,'server_governed_beta_v1');assert.equal(db?.binding,'DB');assert.equal(db?.database_name,'galvivault-0-5-qa');assert.equal(db?.database_id,'cdf9042b-ab09-498a-ac66-010b6cce47d4');});
test('Human E2E and release evidence remain fail-closed rather than auto-passed',()=>{const runbook=read('release-evidence/day7/day7-human-e2e-runbook.md');for(const id of req.human_e2e.map(x=>x.id)) assert.match(runbook,new RegExp(id));for(const id of req.golden_cases.map(x=>`Golden ${x.id}`)) assert.match(runbook,new RegExp(id));assert.match(runbook,/manual_repair=NO/);assert.match(runbook,/Do not promote `main`/i);});
