// Day 5 H9 recovery re-gate after inherited deployment-ownership assertion correction.
import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
test('Day 8 files exist and public GalviCare remains separate',()=>{for(const p of ['worker/day8-entry.js','worker/auth/operator-identity.js','worker/routes/operator-auth.js','worker/routes/operator-workspace.js','clinician-portal/index.html','clinician-portal/app.js','clinician-portal/styles.css','wrangler.day8.json','migrations/day8/0006_operator_device_auth.sql','migrations/day8/0007_second_galviclinician_invitation.sql'])assert.ok(fs.existsSync(p));assert.ok(!read('worker/day8-entry.js').includes("'./worker.js'"));});
test('Worker-native identity fails closed and legacy headers are replaced only after session validation',()=>{const a=read('worker/routes/operator-auth.js'),s=read('worker/auth/operator-identity.js');assert.match(a,/gv8_operator_sessions/);assert.match(a,/crypto\.subtle\.verify/);assert.match(a,/ECDSA/);assert.match(a,/P-256/);assert.match(a,/HttpOnly; Secure; SameSite=Strict/);assert.match(s,/resolveClinicianSession/);assert.match(s,/h\.delete\('X-Galvi-Role'\)/);assert.doesNotMatch(a,/Cf-Access-Jwt-Assertion|CF_ACCESS_/);});
test('enrollment stores public credentials and no plaintext password or reusable enrollment secret',()=>{const a=read('worker/routes/operator-auth.js'),m=read('migrations/day8/0006_operator_device_auth.sql');assert.match(a,/BUSINESS_PHYSICIAN_ENROLLMENT_HASH/);assert.match(a,/public_jwk/);assert.match(m,/public_jwk TEXT NOT NULL/);assert.match(m,/session_hash TEXT PRIMARY KEY/);assert.doesNotMatch(m,/password/i);assert.doesNotMatch(read('wrangler.day8.json'),/Q-mochwq2ZzOcdJdhtM0GZkHl52gUoOT/);});
test('Business Physician QA device recovery consumes one rotated bootstrap code, disables prior device, and revokes prior sessions',()=>{const a=read('worker/routes/operator-auth.js'),w=JSON.parse(read('wrangler.day8.json'));assert.match(a,/bootstrapUse/);assert.match(a,/deviceReplaced/);assert.match(a,/status='disabled'/);assert.match(a,/UPDATE gv8_operator_sessions SET revoked_at/);assert.match(a,/qa_business_physician_bootstrap/);assert.match(a,/enrollment_code_consumed:true/);assert.match(a,/one-time code has already been used/);assert.ok(String(w.vars.BUSINESS_PHYSICIAN_ENROLLMENT_HASH||'').length>=40);assert.doesNotMatch(JSON.stringify(w),/gvr1_/);});
test('operator search is bounded and chart is canonical read projection',()=>{const s=read('worker/routes/operator-workspace.js');assert.match(s,/q\.length<3/);assert.match(s,/Math\.min\(raw,25\)/);assert.match(s,/gv1_business_medical_records/);assert.match(s,/getReasoning/);assert.match(s,/getCare/);});
test('portal uses non-extractable device private key, secure session cookie, and protected mutations',()=>{const s=read('clinician-portal/app.js');assert.match(s,/indexedDB/);assert.match(s,/importKey\('pkcs8'.*false/);assert.match(s,/credentials:'include'/);assert.match(s,/cache:'no-store'/);assert.match(s,/Idempotency-Key/);assert.match(s,/status===409/);assert.doesNotMatch(s,/localStorage|sessionStorage/);});
test('E2E-11 treatment create validates same-BMR FK lineage and defers FK enforcement for the atomic batch',()=>{const s=read('worker/day8-entry.js');assert.match(s,/preflightTreatmentPlanFk/);assert.match(s,/gv1_assessment_sessions/);assert.match(s,/session\.bmr_id!==bmrId/);assert.match(s,/gv1_recommendations/);assert.match(s,/gv1_findings/);assert.match(s,/PRAGMA defer_foreign_keys = ON/);assert.match(s,/path==='\/api\/v1\/treatment-plans'/);});
test('E2E-17 clinician role cannot invoke Business Physician-only governance or transition routes',()=>{const s=read('worker/day8-entry.js');assert.match(s,/identity\.role!=='business_physician'/);assert.match(s,/path==='\/api\/v1\/governance\/confirmations'/);assert.match(s,/transitions/);assert.match(s,/physicianOnly/);assert.match(s,/GV_AUTH_FORBIDDEN/);assert.match(s,/Business Physician authorization is required/);});
test('Day 5 active-care routes preserve real clinician role instead of upgrading GalviClinician to operator',()=>{const s=read('worker/day8-entry.js');assert.match(s,/asDay5CareHeaders/);assert.match(s,/galviclinician/);assert.match(s,/activeCarePath/);assert.match(s,/finding-decisions/);assert.match(s,/galviaudit-orders/);assert.match(s,/referrals/);assert.match(s,/reassessments/);});
test('Business Physician portal binds plan to current Clinic brief and canonical Score Shot Sight Path versions',()=>{const s=read('clinician-portal/app.js');assert.match(s,/clinic-brief/);assert.match(s,/brief_fingerprint/);assert.match(s,/source_versions/);assert.match(s,/clinical_priority/);assert.match(s,/target_metrics/);assert.match(s,/monitoring_plan/);assert.match(s,/escalation_triggers/);});
test('Business Physician portal exposes Rx Audit referral reassessment and returned-result actions',()=>{const s=read('clinician-portal/app.js');for(const marker of ['/api/v1/galvirx','/api/v1/galviaudit-orders','/api/v1/referrals','/api/v1/reassessments','/result','/outcome'])assert.ok(s.includes(marker),marker);});
test('second GalviClinician provisioning is additive and invitation-only',()=>{const m=read('migrations/day8/0007_second_galviclinician_invitation.sql');assert.match(m,/op_galviclinician_qa_01/);assert.match(m,/role,/);assert.match(m,/'clinician'/);assert.match(m,/gv8_operator_invitations/);assert.doesNotMatch(m,/password/i);});
test('QA config is isolated and no Zero Trust prerequisite remains',()=>{const w=JSON.parse(read('wrangler.day8.json'));assert.equal(w.name,'galvivault-day8-qa');assert.equal(w.vars.ENVIRONMENT,'qa');assert.equal(w.vars.MIN_SCHEMA_VERSION,'0006');assert.equal(w.d1_databases[0].database_name,'galvivault-0-5-qa');assert.ok(!JSON.stringify(w).includes('production'));assert.ok(!JSON.stringify(w).includes('CF_ACCESS_'));});
