-- GALVICARE 0.5 QA D1 BASELINE
-- Snapshot of the schema that completed Day 1
-- Database: galvivault-0-5-qa
-- This file documents the current state.
-- Do not run against production.
type	name	tbl_name	sql
index	idx_events_session_created	journey_events	CREATE INDEX idx_events_session_created ON journey_events(session_id, created_at)
index	idx_evidence_session_product	clinical_evidence	CREATE INDEX idx_evidence_session_product ON clinical_evidence(session_id, product)
index	idx_followups_session_product	clinical_followups	CREATE INDEX idx_followups_session_product ON clinical_followups(session_id, product)
index	idx_founders_email	founders	CREATE UNIQUE INDEX idx_founders_email ON founders(email) WHERE email IS NOT NULL
index	idx_founders_session	founders	CREATE INDEX idx_founders_session ON founders(session_id)
index	idx_hypotheses_session	clinical_hypotheses	CREATE INDEX idx_hypotheses_session ON clinical_hypotheses(session_id)
index	idx_observations_session	clinical_observations	CREATE INDEX idx_observations_session ON clinical_observations(session_id)
index	idx_payments_stripe_session	payments	CREATE UNIQUE INDEX idx_payments_stripe_session ON payments(stripe_session_id) WHERE stripe_session_id IS NOT NULL
index	idx_responses_session_product	assessment_responses	CREATE INDEX idx_responses_session_product ON assessment_responses(session_id, product)
index	idx_results_session	product_results	CREATE INDEX idx_results_session ON product_results(session_id)
index	idx_ventures_session	ventures	CREATE INDEX idx_ventures_session ON ventures(session_id)
table	_cf_KV	_cf_KV	CREATE TABLE _cf_KV ( key TEXT PRIMARY KEY, value BLOB ) WITHOUT ROWID
table	assessment_responses	assessment_responses	CREATE TABLE assessment_responses ( response_id TEXT PRIMARY KEY, session_id TEXT NOT NULL, product TEXT NOT NULL, question_id TEXT NOT NULL, dimension TEXT, answer_text TEXT, answer_number REAL, answer_json TEXT, rules_version TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY (session_id) REFERENCES sessions(session_id), UNIQUE(session_id, product, question_id) )
table	clinical_evidence	clinical_evidence	CREATE TABLE clinical_evidence ( evidence_id TEXT PRIMARY KEY, session_id TEXT NOT NULL, founder_id TEXT, venture_id TEXT, product TEXT NOT NULL, source_type TEXT NOT NULL, source_reference TEXT, question_id TEXT, question_version TEXT, raw_text TEXT, normalized_value TEXT, evidence_summary TEXT, consent_scope TEXT, created_at TEXT NOT NULL, FOREIGN KEY (session_id) REFERENCES sessions(session_id) )
table	clinical_feedback	clinical_feedback	CREATE TABLE clinical_feedback ( feedback_id TEXT PRIMARY KEY, session_id TEXT NOT NULL, product TEXT, finding_code TEXT, recommendation_code TEXT, feedback_source TEXT NOT NULL, accuracy_rating INTEGER, relevance_rating INTEGER, confirmed INTEGER, feedback_text TEXT, created_at TEXT NOT NULL, FOREIGN KEY (session_id) REFERENCES sessions(session_id) )
table	clinical_findings	clinical_findings	CREATE TABLE clinical_findings ( finding_id TEXT PRIMARY KEY, session_id TEXT NOT NULL, product TEXT NOT NULL, finding_code TEXT NOT NULL, finding_text TEXT NOT NULL, evidence_ids_json TEXT NOT NULL, hypothesis_ids_json TEXT, severity TEXT, confidence REAL, confidence_band TEXT, status TEXT NOT NULL DEFAULT 'supported', rules_version TEXT NOT NULL, confirmed_by_customer INTEGER, confirmed_by_clinician INTEGER, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY (session_id) REFERENCES sessions(session_id), UNIQUE(session_id, product, finding_code) )
table	clinical_followups	clinical_followups	CREATE TABLE clinical_followups ( followup_id TEXT PRIMARY KEY, session_id TEXT NOT NULL, current_stage TEXT NOT NULL, product TEXT NOT NULL, question_id TEXT NOT NULL, question_text TEXT NOT NULL, answer TEXT, confidence_impact REAL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY (session_id) REFERENCES sessions(session_id), UNIQUE(session_id, product, question_id) )
table	clinical_hypotheses	clinical_hypotheses	CREATE TABLE clinical_hypotheses ( hypothesis_id TEXT PRIMARY KEY, session_id TEXT NOT NULL, product TEXT NOT NULL, hypothesis_code TEXT NOT NULL, hypothesis_text TEXT NOT NULL, supporting_observation_ids_json TEXT, alternative_hypotheses_json TEXT, contradiction_evidence_ids_json TEXT, confidence REAL, status TEXT NOT NULL DEFAULT 'candidate', reviewed_by TEXT, reviewed_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY (session_id) REFERENCES sessions(session_id) )
table	clinical_observations	clinical_observations	CREATE TABLE clinical_observations ( observation_id TEXT PRIMARY KEY, session_id TEXT NOT NULL, product TEXT NOT NULL, observation_code TEXT NOT NULL, observation_text TEXT NOT NULL, evidence_ids_json TEXT NOT NULL, confidence REAL, created_by TEXT NOT NULL DEFAULT 'rules', rules_version TEXT, status TEXT NOT NULL DEFAULT 'candidate', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY (session_id) REFERENCES sessions(session_id) )
table	clinical_outcomes	clinical_outcomes	CREATE TABLE clinical_outcomes ( outcome_id TEXT PRIMARY KEY, session_id TEXT NOT NULL, treatment_code TEXT, recommendation_code TEXT, measurement_name TEXT NOT NULL, baseline_value TEXT, target_value TEXT, observed_value TEXT, measurement_date TEXT, outcome_status TEXT, clinician_notes TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY (session_id) REFERENCES sessions(session_id) )
table	entitlements	entitlements	CREATE TABLE entitlements ( entitlement_id TEXT PRIMARY KEY, session_id TEXT NOT NULL, product TEXT NOT NULL, entitlement_status TEXT NOT NULL DEFAULT 'locked', source TEXT, source_reference TEXT, granted_at TEXT, expires_at TEXT, updated_at TEXT NOT NULL, FOREIGN KEY (session_id) REFERENCES sessions(session_id), UNIQUE(session_id, product) )
table	fcd_notes	fcd_notes	CREATE TABLE fcd_notes ( note_id TEXT PRIMARY KEY, session_id TEXT NOT NULL, facilitator_name TEXT, discussion_summary TEXT, objections TEXT, clinical_observations TEXT, recommended_next_step TEXT, upsell_status TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY (session_id) REFERENCES sessions(session_id) )
table	founders	founders	CREATE TABLE founders ( founder_id TEXT PRIMARY KEY, session_id TEXT NOT NULL, first_name TEXT, last_name TEXT, email TEXT, phone TEXT, linkedin_url TEXT, consent_status TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY (session_id) REFERENCES sessions(session_id) )
table	journey_events	journey_events	CREATE TABLE journey_events ( event_id TEXT PRIMARY KEY, session_id TEXT, event_name TEXT NOT NULL, product TEXT, current_stage TEXT, event_json TEXT, created_at TEXT NOT NULL )
table	knowledge_items	knowledge_items	CREATE TABLE knowledge_items ( knowledge_item_id TEXT PRIMARY KEY, item_type TEXT NOT NULL, item_code TEXT NOT NULL, internal_label TEXT, customer_label TEXT, content_json TEXT NOT NULL, approval_status TEXT NOT NULL DEFAULT 'draft', version TEXT NOT NULL, effective_from TEXT, effective_to TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(item_type, item_code, version) )
table	learning_candidates	learning_candidates	CREATE TABLE learning_candidates ( learning_candidate_id TEXT PRIMARY KEY, candidate_type TEXT NOT NULL, candidate_code TEXT, candidate_summary TEXT NOT NULL, supporting_case_count INTEGER NOT NULL DEFAULT 1, supporting_record_ids_json TEXT, status TEXT NOT NULL DEFAULT 'proposed', reviewed_by TEXT, decision_notes TEXT, approved_rules_version TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL )
table	payments	payments	CREATE TABLE payments ( payment_id TEXT PRIMARY KEY, session_id TEXT NOT NULL, product TEXT NOT NULL, stripe_session_id TEXT, stripe_payment_intent_id TEXT, amount_cents INTEGER, currency TEXT DEFAULT 'usd', payment_status TEXT NOT NULL DEFAULT 'unpaid', paid_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY (session_id) REFERENCES sessions(session_id) )
table	product_results	product_results	CREATE TABLE product_results ( result_id TEXT PRIMARY KEY, session_id TEXT NOT NULL, product TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft', confidence REAL, confidence_band TEXT, result_json TEXT NOT NULL, generation_source TEXT NOT NULL DEFAULT 'rules', rules_version TEXT, content_version TEXT, generated_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY (session_id) REFERENCES sessions(session_id), UNIQUE(session_id, product) )
table	recommendations	recommendations	CREATE TABLE recommendations ( recommendation_id TEXT PRIMARY KEY, session_id TEXT NOT NULL, product TEXT NOT NULL, recommendation_code TEXT NOT NULL, recommendation_text TEXT NOT NULL, finding_codes_json TEXT, priority INTEGER, status TEXT NOT NULL DEFAULT 'recommended', rules_version TEXT NOT NULL, customer_response TEXT, clinician_response TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY (session_id) REFERENCES sessions(session_id), UNIQUE(session_id, product, recommendation_code) )
table	release_metadata	release_metadata	CREATE TABLE release_metadata ( metadata_key TEXT PRIMARY KEY, metadata_value TEXT NOT NULL, updated_at TEXT NOT NULL )
table	sessions	sessions	CREATE TABLE sessions ( session_id TEXT PRIMARY KEY, current_stage TEXT NOT NULL DEFAULT 'Welcome', status TEXT NOT NULL DEFAULT 'active', source TEXT, utm_source TEXT, utm_medium TEXT, utm_campaign TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, last_seen_at TEXT NOT NULL )
table	system_errors	system_errors	CREATE TABLE system_errors ( error_id TEXT PRIMARY KEY, session_id TEXT, action TEXT, error_code TEXT, error_message TEXT, error_json TEXT, environment TEXT NOT NULL DEFAULT 'qa', created_at TEXT NOT NULL )
table	treatment_records	treatment_records	CREATE TABLE treatment_records ( treatment_record_id TEXT PRIMARY KEY, session_id TEXT NOT NULL, treatment_code TEXT NOT NULL, source_product TEXT, indication_codes_json TEXT, treatment_status TEXT NOT NULL DEFAULT 'recommended', outcome_target TEXT, started_at TEXT, completed_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY (session_id) REFERENCES sessions(session_id) )
table	ventures	ventures	CREATE TABLE ventures ( venture_id TEXT PRIMARY KEY, session_id TEXT NOT NULL, founder_id TEXT, venture_name TEXT, organization_type TEXT, stage TEXT, industry TEXT, revenue_range TEXT, primary_goal TEXT, primary_challenge TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY (session_id) REFERENCES sessions(session_id), FOREIGN KEY (founder_id) REFERENCES founders(founder_id) )
