import fs from 'node:fs';

const base=String(process.env.DAY4_BASE_URL||'').replace(/\/$/,'');
const origin=process.env.DAY4_ALLOWED_ORIGIN||'https://galvipro.com';
const suffix=String(process.env.DAY4_RUN_SUFFIX||Date.now()).replace(/[^A-Za-z0-9._-]/g,'_').toLowerCase();
const evidencePath=process.env.DAY4_EVIDENCE_PATH||`release-evidence/day4/h4-${suffix}.json`;
if(!base) throw new Error('DAY4_BASE_URL is required.');
const out={day:4,run_suffix:suffix,base_url:base,origin,started_at:new Date().toISOString(),steps:[],ids:{}};
const assert=(c,m)=>{if(!c)throw new Error(m)};
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
function headers(step,{body,key,role,actorId}={}){const h=new Headers({Origin:origin,'Cache-Control':'no-cache','X-Correlation-Id':`corr_d4_${suffix}_${step.toLowerCase().replace(/[^a-z0-9]+/g,'_')}`});if(body!==undefined)h.set('Content-Type','application/json');if(key)h.set('Idempotency-Key',key);if(role)h.set('X-Galvi-Role',role);if(actorId)h.set('X-Galvi-Actor-Id',actorId);return h}
async function parse(r){const t=await r.text();try{return JSON.parse(t)}catch{return {non_json_response:t.slice(0,500)}}}
async function req(step,path,{method='GET',body,key,role,actorId,expected=[200]}={}){const r=await fetch(`${base}${path}`,{method,headers:headers(step,{body,key,role,actorId}),cache:'no-store',...(body!==undefined?{body:JSON.stringify(body)}:{})});const p=await parse(r);const rec={step,timestamp:new Date().toISOString(),method,path,status:r.status,correlation_id:r.headers.get('x-correlation-id'),environment:r.headers.get('x-galvivault-environment'),request:body??null,response:p};out.steps.push(rec);assert(expected.includes(r.status),`${step}: expected ${expected} got ${r.status} ${JSON.stringify(p)}`);assert(rec.environment==='qa',`${step}: not QA`);assert(rec.correlation_id,`${step}: no correlation`);return {r,p,rec}}
async function ready(){let pass=0,last;for(let i=1;i<=50;i++){const x=await req(`H4.0_READINESS_${i}`,`/api/v1/day4/readiness?probe=${i}`);last=x;if(x.p?.data?.ready===true&&x.p?.data?.current_schema_version==='0004'&&x.p?.meta?.schema_version==='0004')pass++;else pass=0;if(pass>=3)return x;await sleep(1500)}throw new Error(`Day4 runtime did not converge: ${JSON.stringify(last?.p)}`)}
function identity(x){const i=x.p?.data?.identity;assert(i,'identity missing');return {founder_id:i.founder?.founder_id,venture_id:i.venture?.venture_id,bmr_id:i.business_medical_record?.bmr_id,session_id:i.session?.session_id,bmr_version:Number(i.business_medical_record?.record_version||0)}}
try{
 await ready();
 const sessionBody={client_session_key:`d4-session-${suffix}-01`,source:'galvivault',current_stage:'GalviTriage',founder:{email:`founder.day4.${suffix}@example.test`,first_name:'Day',last_name:'Four',consent_status:'approved'},venture:{venture_name:`Day 4 Reasoning Venture ${suffix}`,stage:'validation',industry:'business-services',role_code:'founder',is_primary:true}};
 const id1=identity(await req('H4.1_IDENTITY','/api/v1/sessions',{method:'POST',body:sessionBody,key:`d4-id-${suffix}`,expected:[201]}));Object.assign(out.ids,id1);
 const evBody={bmr_id:id1.bmr_id,session_id:id1.session_id,source_type:'assessment_answer',source_ref:`triage.problem_clarity:v1:${suffix}`,value_type:'number',value_number:72,consent_status:'approved',captured_at:new Date().toISOString(),assessment_answer:{question_id:'triage.problem_clarity',question_version:'v1',raw_value_number:72,normalized_value_number:72,confidence_effect:0.2}};
 const ev=await req('H4.1_EVIDENCE','/api/v1/evidence',{method:'POST',body:evBody,key:`d4-evidence-${suffix}`,expected:[201]});const evidenceId=ev.p?.data?.evidence?.evidence_id;assert(evidenceId,'evidence id missing');out.ids.evidence_id=evidenceId;
 await req('H4.1_ACCEPT',`/api/v1/evidence/${evidenceId}/accept`,{method:'POST',body:{reason:'day4_precondition'},key:`d4-accept-${suffix}`,role:'operator',actorId:'day4_qa_operator'});
 await req('H4.1_BASELINE',`/api/v1/business-medical-records/${id1.bmr_id}/evidence?view=history`);
 const obsBody={bmr_id:id1.bmr_id,statement:'Observed quantified problem clarity signal from accepted assessment evidence.',domain:'problem_clarity',confidence:90,source_type:'deterministic_rule',source_version:'day4_qa_v1',evidence:[{evidence_id:evidenceId,support_type:'supports'}]};
 const obs=await req('H4.2_SUPPORTED_OBSERVATION','/api/v1/observations',{method:'POST',body:obsBody,key:`d4-obs-${suffix}`,expected:[201]});const observationId=obs.p?.data?.observation?.observation_id;assert(observationId,'observation id missing');out.ids.observation_id=observationId;
 const noObs=await req('H4.3_UNSUPPORTED_OBSERVATION','/api/v1/observations',{method:'POST',body:{...obsBody,evidence:[]},key:`d4-obs-neg-${suffix}`,expected:[422]});assert(noObs.p?.error?.code==='GV_LINEAGE_REQUIRED','wrong observation lineage error');
 const hypBody={bmr_id:id1.bmr_id,statement:'The venture may benefit from further problem-definition validation.',domain:'problem_clarity',confidence:65,uncertainty:'This remains a hypothesis pending additional evidence.',source_type:'deterministic_rule',source_version:'day4_qa_v1',observations:[{observation_id:observationId,relationship_type:'supports'}]};
 const hyp=await req('H4.4_SUPPORTED_HYPOTHESIS','/api/v1/hypotheses',{method:'POST',body:hypBody,key:`d4-hyp-${suffix}`,expected:[201]});const hypothesisId=hyp.p?.data?.hypothesis?.hypothesis_id;assert(hypothesisId,'hypothesis id missing');out.ids.hypothesis_id=hypothesisId;assert(hyp.p?.data?.hypothesis?.uncertainty,'uncertainty missing');
 await req('H4.5_UNSUPPORTED_HYPOTHESIS','/api/v1/hypotheses',{method:'POST',body:{...hypBody,observations:[]},key:`d4-hyp-neg-${suffix}`,expected:[422]});
 const findBody={bmr_id:id1.bmr_id,finding_code:'D4_QA_PROBLEM_CLARITY',headline:'Problem clarity requires review',statement:'Current evidence supports a governed finding that problem clarity should be reviewed.',domain:'problem_clarity',confidence:82,confirmation_status:'unconfirmed',source_type:'deterministic_rule',source_version:'day4_qa_v1',support:{evidence:[{evidence_id:evidenceId,support_type:'supports'}],observations:[{observation_id:observationId,support_type:'supports'}],hypotheses:[{hypothesis_id:hypothesisId,relationship_type:'derived_from'}]}};
 const finding=await req('H4.6_SUPPORTED_FINDING','/api/v1/findings',{method:'POST',body:findBody,key:`d4-find-${suffix}`,expected:[201]});const findingId=finding.p?.data?.finding?.finding_id;assert(findingId,'finding id missing');out.ids.finding_v1=findingId;assert(finding.p?.data?.finding?.confirmation_status==='unconfirmed','finding self-confirmed');
 await req('H4.7_UNSUPPORTED_FINDING','/api/v1/findings',{method:'POST',body:{...findBody,support:{evidence:[],observations:[],hypotheses:[]}},key:`d4-find-neg-${suffix}`,expected:[422]});
 const replay=await req('H4.8_FINDING_REPLAY','/api/v1/findings',{method:'POST',body:findBody,key:`d4-find-${suffix}`,expected:[200]});assert(replay.p?.meta?.idempotent_replay===true,'finding replay flag missing');assert(replay.p?.data?.finding?.finding_id===findingId,'finding replay changed id');
 const confirmBody={finding_id:findingId,decision:'confirm',reason:'Authorized Day 4 QA confirmation',expected_version:1};
 const conf=await req('H4.9_AUTHORIZED_CONFIRMATION','/api/v1/governance/confirmations',{method:'POST',body:confirmBody,key:`d4-confirm-${suffix}`,role:'operator',actorId:'day4_qa_operator'});assert(conf.p?.data?.finding?.confirmation_status==='confirmed','finding not confirmed');
 const secondFinding=await req('H4.10_SECOND_FINDING','/api/v1/findings',{method:'POST',body:{...findBody,finding_code:'D4_QA_UNAUTH',statement:'Synthetic finding for authorization denial.'},key:`d4-find-unauth-${suffix}`,expected:[201]});const secondFindingId=secondFinding.p?.data?.finding?.finding_id;
 await req('H4.10_UNAUTHORIZED_CONFIRMATION','/api/v1/governance/confirmations',{method:'POST',body:{finding_id:secondFindingId,decision:'confirm',reason:'must fail',expected_version:1},key:`d4-confirm-unauth-${suffix}`,expected:[403]});
 const supBody={expected_version:1,reason:'Material Day 4 QA revision',statement:'Revised governed finding after additional review.',domain:'problem_clarity',finding_code:'D4_QA_PROBLEM_CLARITY',headline:'Problem clarity reviewed',confidence:86,source_type:'operator_review',source_version:'day4_qa_v2'};
 const stale=await req('H4.11_STALE_VERSION',`/api/v1/findings/${findingId}/supersede`,{method:'POST',body:{...supBody,expected_version:0},key:`d4-sup-stale-${suffix}`,role:'operator',actorId:'day4_qa_operator',expected:[409]});assert(stale.p?.error?.code==='GV_VERSION_CONFLICT','wrong stale-version error');
 const sup=await req('H4.12_SUPERSEDE_FINDING',`/api/v1/findings/${findingId}/supersede`,{method:'POST',body:supBody,key:`d4-sup-${suffix}`,role:'operator',actorId:'day4_qa_operator',expected:[201]});const findingV2=sup.p?.data?.finding;assert(Number(findingV2?.version_no)===2&&findingV2?.supersedes_finding_id===findingId,'supersession invalid');out.ids.finding_v2=findingV2.finding_id;
 const current=await req('H4.13_CURRENT',`/api/v1/business-medical-records/${id1.bmr_id}/reasoning`);assert(current.p?.data?.findings?.some(x=>x.finding_id===findingV2.finding_id),'v2 not current');
 const history=await req('H4.13_HISTORY',`/api/v1/business-medical-records/${id1.bmr_id}/reasoning?history=true&limit=100`,{role:'operator',actorId:'day4_qa_operator'});assert(history.p?.data?.findings?.some(x=>x.finding_id===findingId)&&history.p?.data?.findings?.some(x=>x.finding_id===findingV2.finding_id),'finding history incomplete');
 const timeline=await req('H4.14_TIMELINE',`/api/v1/business-medical-records/${id1.bmr_id}/timeline`,{role:'operator',actorId:'day4_qa_operator'});for(const type of ['session','evidence','observation','hypothesis','finding','governance'])assert(timeline.p?.data?.entries?.some(x=>x.entry_type===type),`timeline missing ${type}`);
 const customer=await req('H4.15_CUSTOMER_PROJECTION',`/api/v1/business-medical-records/${id1.bmr_id}/customer-projection`);const cj=JSON.stringify(customer.p?.data||{});for(const forbidden of ['confirmation_reason','confirmed_by_id','created_by_id','audit_log','hypotheses','observations'])assert(!cj.includes(forbidden),`customer projection leaked ${forbidden}`);
 const secondSessionBody={client_session_key:`d4-session-${suffix}-02`,source:'galvivault',current_stage:'GalviTriage',founder:{email:`founder.day4.second.${suffix}@example.test`,first_name:'Second',last_name:'Scope',consent_status:'approved'},venture:{venture_name:`Day 4 Second Venture ${suffix}`,stage:'ideation',role_code:'founder',is_primary:true}};
 const id2=identity(await req('H4.16_SECOND_SCOPE','/api/v1/sessions',{method:'POST',body:secondSessionBody,key:`d4-id2-${suffix}`,expected:[201]}));
 const ev2=await req('H4.16_SECOND_EVIDENCE','/api/v1/evidence',{method:'POST',body:{...evBody,bmr_id:id2.bmr_id,session_id:id2.session_id,source_ref:`cross:${suffix}`},key:`d4-ev2-${suffix}`,expected:[201]});const evidence2=ev2.p?.data?.evidence?.evidence_id;
 await req('H4.16_CROSS_BMR_NEGATIVE','/api/v1/observations',{method:'POST',body:{...obsBody,evidence:[{evidence_id:evidence2,support_type:'supports'}]},key:`d4-cross-${suffix}`,expected:[403]});
 const t1=await req('H4.17_TO_ASSESSMENT',`/api/v1/business-medical-records/${id1.bmr_id}/transitions`,{method:'POST',body:{to_status:'assessment_in_progress',expected_version:id1.bmr_version,reason_code:'day4_assessment'},key:`d4-life1-${suffix}`,role:'operator',actorId:'day4_qa_operator'});const v2=Number(t1.p?.data?.bmr?.record_version);assert(t1.p?.data?.bmr?.status==='assessment_in_progress','assessment transition failed');
 const tr=await req('H4.17_TRANSITION_REPLAY',`/api/v1/business-medical-records/${id1.bmr_id}/transitions`,{method:'POST',body:{to_status:'assessment_in_progress',expected_version:id1.bmr_version,reason_code:'day4_assessment'},key:`d4-life1-${suffix}`,role:'operator',actorId:'day4_qa_operator'});assert(tr.p?.meta?.idempotent_replay===true,'transition replay failed');
 await req('H4.17_STALE_TRANSITION',`/api/v1/business-medical-records/${id1.bmr_id}/transitions`,{method:'POST',body:{to_status:'under_review',expected_version:id1.bmr_version,reason_code:'day4_review'},key:`d4-life-stale-${suffix}`,role:'operator',actorId:'day4_qa_operator',expected:[409]});
 const t2=await req('H4.17_UNDER_REVIEW',`/api/v1/business-medical-records/${id1.bmr_id}/transitions`,{method:'POST',body:{to_status:'under_review',expected_version:v2,reason_code:'day4_review'},key:`d4-life2-${suffix}`,role:'operator',actorId:'day4_qa_operator'});assert(t2.p?.data?.bmr?.status==='under_review','under_review failed');
 const refresh=await req('H4.18_REFRESH_CURRENT',`/api/v1/business-medical-records/${id1.bmr_id}/reasoning`);assert(refresh.p?.data?.findings?.some(x=>x.finding_id===findingV2.finding_id),'refresh lost current finding');
 await req('H4.18_REFRESH_TIMELINE',`/api/v1/business-medical-records/${id1.bmr_id}/timeline`,{role:'operator',actorId:'day4_qa_operator'});
 out.steps.push({step:'H4.19_PRODUCTION_REGRESSION',status:'delegated_to_workflow',timestamp:new Date().toISOString()});
 out.finished_at=new Date().toISOString();out.status='pass';fs.mkdirSync(new URL('../release-evidence/day4/',import.meta.url),{recursive:true});fs.writeFileSync(evidencePath,JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));
}catch(error){out.finished_at=new Date().toISOString();out.status='fail';out.error=String(error?.stack||error);try{fs.mkdirSync(new URL('../release-evidence/day4/',import.meta.url),{recursive:true});fs.writeFileSync(evidencePath,JSON.stringify(out,null,2))}catch{}console.error(error);process.exit(1)}
