const API=globalThis.GALVIVAULT_API_BASE||'';
const $=s=>document.querySelector(s); let chart=null, selected=null, retry=new Map();
const tabs=['Overview','Timeline','Evidence','Findings','Care Plan','GalviClinic Session','Outcomes / Follow-up'];
const enc=new TextEncoder();
const b64u=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const vals=f=>Object.fromEntries(new FormData(f));

async function api(path,opt={}){
  const res=await fetch(API+path,{credentials:'include',cache:'no-store',...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});
  const body=await res.json().catch(()=>({}));
  if(!res.ok){const e=new Error(body?.error?.message||`Request failed (${res.status})`);e.status=res.status;e.code=body?.error?.code;throw e;} return body.data;
}

function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open('galvivault-day8-auth',1);r.onupgradeneeded=()=>r.result.createObjectStore('keys');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function putKey(id,key){const d=await db();await new Promise((resolve,reject)=>{const t=d.transaction('keys','readwrite');t.objectStore('keys').put(key,id);t.oncomplete=resolve;t.onerror=()=>reject(t.error)})}
async function getKey(id){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction('keys').objectStore('keys').get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function createDeviceKey(){const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);const public_jwk=await crypto.subtle.exportKey('jwk',pair.publicKey);const pkcs8=await crypto.subtle.exportKey('pkcs8',pair.privateKey);const privateKey=await crypto.subtle.importKey('pkcs8',pkcs8,{name:'ECDSA',namedCurve:'P-256'},false,['sign']);return {public_jwk,privateKey}}

function clear(){chart=null;selected=null;$('#workspace').hidden=true;$('#chart').hidden=true;$('#results').replaceChildren();$('#logout').hidden=true;}
function showAuth(message){clear();$('#status').textContent=message;$('#authForms').hidden=false;}
async function load(){
  try{const me=await api('/api/v1/operator/me');$('#status').textContent=`Signed in: ${me.display_name} (${me.role})`;$('#authForms').hidden=true;$('#workspace').hidden=false;$('#logout').hidden=false;window.operator=me;}
  catch(e){showAuth(e.status===401?'Secure clinician sign-in is required.':e.message);}
}

$('#enroll').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,msg=f.querySelector('.msg'),p=vals(f);f.querySelector('button').disabled=true;try{const credential_id=`cred_${crypto.randomUUID().replaceAll('-','')}`;const {public_jwk,privateKey}=await createDeviceKey();await api('/api/v1/operator/auth/enroll',{method:'POST',body:JSON.stringify({email:p.email,enrollment_token:p.enrollment_token,credential_id,public_jwk})});await putKey(credential_id,privateKey);f.reset();msg.textContent='Device enrolled securely.';await load();}catch(err){msg.textContent=err.message;}finally{f.querySelector('button').disabled=false}});

$('#login').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,msg=f.querySelector('.msg'),p=vals(f);f.querySelector('button').disabled=true;try{const options=await api('/api/v1/operator/auth/login/options',{method:'POST',body:JSON.stringify({email:p.email})});const key=await getKey(options.credential_id);if(!key)throw new Error('This browser is not enrolled for that clinician. Use the one-time enrollment flow on this approved device.');const sig=await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},key,enc.encode(options.challenge));await api('/api/v1/operator/auth/login/verify',{method:'POST',body:JSON.stringify({challenge_id:options.challenge_id,credential_id:options.credential_id,signature:b64u(sig)})});msg.textContent='';await load();}catch(err){msg.textContent=err.message;}finally{f.querySelector('button').disabled=false}});

$('#search').addEventListener('submit',async e=>{e.preventDefault();try{const d=await api(`/api/v1/operator/founders?query=${encodeURIComponent($('#query').value)}&limit=25`);$('#results').innerHTML=d.items.map(x=>`<button class="card result" data-bmr="${x.bmr_id}">${x.first_name||''} ${x.last_name||''} — ${x.venture_name} — ${x.bmr_status} v${x.record_version}</button>`).join('');}catch(e){if(e.status===401)return load();$('#results').textContent=e.message;}});
$('#results').addEventListener('click',e=>{const b=e.target.closest('[data-bmr]');if(b)openChart(b.dataset.bmr)});
async function openChart(id){
  selected=id;$('#panel').textContent='Loading…';
  try{
    chart=await api(`/api/v1/operator/business-medical-records/${encodeURIComponent(id)}/chart`);
    try{chart.active_care=await api(`/api/v1/business-medical-records/${encodeURIComponent(id)}/clinic-brief`)}catch(error){chart.active_care_error={message:error.message,code:error.code||null}}
  }catch(e){if(e.status===401)return load();throw e}
  if(selected!==id)return;$('#chart').hidden=false;$('#chartTitle').textContent=`${chart.identity.founder.first_name||''} ${chart.identity.founder.last_name||''} — ${chart.identity.venture.venture_name}`;$('#tabs').innerHTML=tabs.map((t,i)=>`<button data-tab="${i}">${t}</button>`).join('');render(0)
}
$('#tabs').addEventListener('click',e=>{if(e.target.dataset.tab)render(Number(e.target.dataset.tab))});
function esc(x){return String(x??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
const arr=v=>Array.isArray(v)?v:[];
const first=(o,keys,blank='—')=>{for(const k of keys){if(o?.[k]!==undefined&&o?.[k]!==null&&String(o[k]).trim()!=='')return o[k]}return blank};
const kv=(label,value)=>`<p><strong>${esc(label)}:</strong> ${esc(value)}</p>`;
const empty=label=>`<p>No ${esc(label)} recorded for this canonical BMR.</p>`;
function reasoningSection(title,items,type){
  if(!items.length)return `<section class="card"><h3>${esc(title)}</h3>${empty(title.toLowerCase())}</section>`;
  return `<section class="card"><h3>${esc(title)}</h3>${items.map(x=>`<article class="record ${esc(type)}">${kv('ID',first(x,[`${type}_id`,'id']))}${kv('Statement',first(x,['statement','description','text']))}${kv('Status',first(x,['confirmation_status','status']))}${kv('Confidence',first(x,['confidence']))}${kv('Source',`${first(x,['source_type'])} ${first(x,['source_version'],'')}`.trim())}${kv('Version',first(x,['version_no','version','record_version']))}${type==='finding'?kv('Governance version',first(x,['governance_version'])):''}${kv('Support count',arr(x.support).length)}</article>`).join('')}</section>`;
}
function renderReasoning(){const r=chart.reasoning||{};return `<div class="clinical-projection"><h2>Current Reasoning</h2>${reasoningSection('Observations',arr(r.observations),'observation')}${reasoningSection('Hypotheses',arr(r.hypotheses),'hypothesis')}${reasoningSection('Findings',arr(r.findings),'finding')}</div>`;}
function careSection(title,items,type){
  if(!items.length)return `<section class="card"><h3>${esc(title)}</h3>${empty(title.toLowerCase())}</section>`;
  return `<section class="card"><h3>${esc(title)}</h3>${items.map(x=>`<article class="record ${esc(type)}">${kv('ID',first(x,[`${type}_id`,'id','rx_id','audit_order_id','referral_id','checkin_id','milestone_id','reassessment_id']))}${kv('Title',first(x,['title','name','objective','description','intervention_code','domain','category','milestone_code','decision']))}${kv('Status',first(x,['status','disposition','adherence_state','decision']))}${kv('Code',first(x,[`${type}_code`,'code','action_code','outcome_code']))}${kv('Version',first(x,['version','version_no','record_version']))}${kv('Created',first(x,['created_at','occurred_at','observed_at','measured_at','updated_at']))}</article>`).join('')}</section>`;
}
function renderCare(){const c=chart.care||{},a=chart.active_care||{};return `<div class="clinical-projection"><h2>Current Care</h2>${careSection('Recommendations',arr(c.recommendations),'recommendation')}${careSection('Treatment Plans',arr(a.treatment_plans).length?arr(a.treatment_plans):arr(c.treatment_plans),'treatment_plan')}${careSection('GalviRx',arr(a.galvirx),'galvirx')}${careSection('GalviAudit / GalviLab',arr(a.galviaudit_orders),'galviaudit')}${careSection('Referrals',arr(a.referrals),'referral')}${careSection('Check-ins',arr(a.checkins),'checkin')}${careSection('Milestones',arr(a.milestones),'milestone')}${careSection('Reassessments',arr(a.reassessments),'reassessment')}${careSection('Treatment Events',arr(c.treatment_events),'treatment_event')}${careSection('Outcomes',arr(c.outcomes),'outcome')}${careSection('Feedback / Follow-up',arr(c.feedback),'feedback')}</div>`;}
function timelineCard(x){return `<article class="card record timeline-entry"><h3>${esc(first(x,['safe_summary','title','statement','source_reference','entry_type'],'Clinical record event'))}</h3>${kv('Type',first(x,['entry_type','type']))}${kv('Canonical ID',first(x,['canonical_id','entity_id','id']))}${kv('Version',first(x,['version_no','version','record_version']))}${kv('Occurred',first(x,['occurred_at','created_at','observed_at','captured_at','updated_at']))}${kv('Source',first(x,['source','source_type','source_product']))}${kv('Correlation ID',first(x,['correlation_id']))}</article>`;}
function projectedTimeline(){
  const direct=arr(chart.timeline).length?arr(chart.timeline):arr(chart.entries);
  if(direct.length)return direct;
  const r=chart.reasoning||{},c=chart.care||{},a=chart.active_care||{};
  const typed=[];
  const add=(items,type,idKeys)=>arr(items).forEach(x=>typed.push({...x,entry_type:type,canonical_id:first(x,idKeys),occurred_at:first(x,['occurred_at','created_at','observed_at','captured_at','updated_at'],''),source:first(x,['source','source_type','source_product'],'')}));
  add(chart.evidence,'evidence',['evidence_id','id']);add(r.observations,'observation',['observation_id','id']);add(r.hypotheses,'hypothesis',['hypothesis_id','id']);add(r.findings,'finding',['finding_id','id']);add(c.recommendations,'recommendation',['recommendation_id','id']);add(a.treatment_plans.length?a.treatment_plans:c.treatment_plans,'treatment_plan',['treatment_plan_id','id']);add(a.galvirx,'galvirx',['rx_id','id']);add(a.galviaudit_orders,'galviaudit',['audit_order_id','id']);add(a.referrals,'referral',['referral_id','id']);add(a.checkins,'checkin',['checkin_id','id']);add(a.milestones,'milestone',['milestone_id','id']);add(a.reassessments,'reassessment',['reassessment_id','id']);add(c.treatment_events,'treatment_event',['treatment_event_id','id']);add(c.outcomes,'outcome',['outcome_id','id']);add(c.feedback,'feedback',['feedback_id','id']);
  return typed.sort((a,b)=>String(first(a,['occurred_at'],'')).localeCompare(String(first(b,['occurred_at'],''))));
}
function renderTimeline(){const items=projectedTimeline();return `<div class="clinical-projection"><h2>Longitudinal Timeline</h2>${items.length?items.map(timelineCard).join(''):empty('timeline events')}</div>`;}
function evidenceCard(x){const value=first(x,['value_text','safe_summary','content','statement'],'—');return `<article class="card record evidence-entry"><h3>${esc(first(x,['source_reference','source_ref','evidence_type'],'Evidence'))}</h3>${kv('Evidence ID',first(x,['evidence_id','id']))}${kv('Type',first(x,['evidence_type','value_type','source_type']))}${kv('Source',first(x,['source_product','source_type']))}${kv('Source reference',first(x,['source_reference','source_ref']))}${kv('Value',typeof value==='object'?JSON.stringify(value):value)}${kv('Confidence',first(x,['confidence']))}${kv('Version',first(x,['evidence_version','version_no','version']))}${kv('Captured / created',first(x,['captured_at','created_at','observed_at']))}</article>`;}
function renderEvidence(){const items=arr(chart.evidence);return `<div class="clinical-projection"><h2>Evidence & Source Material</h2>${items.length?items.map(evidenceCard).join(''):empty('evidence records')}</div>`;}
function renderHistoricalContext(){const f=chart.historical_founder_context;if(!f)return chart.historical_context_error?`<section class="card"><h2>Historical Founder Context / FHR</h2><p>Optional historical context is temporarily unavailable. Correlation ID: ${esc(chart.historical_context_error.correlation_id)}</p></section>`:'';const facts=[...Object.values(f.founder_snapshot||{}),...Object.values(f.genome||{})];return `<section class="card historical-founder-context"><h2>Historical Founder Context / FHR</h2><p><strong>Historical Founder Context — FCD/GalviShot, as of ${esc(f.context_as_of||'source version')}</strong></p><p>This governed history is context only; it is not a current finding, recommendation, treatment, or outcome.</p>${facts.map(x=>`<article class="record">${kv('Historical value',x.value)}${kv('As of',x.as_of)}${kv('Evidence',x.evidence_ref)}${kv('Observation',x.observation_ref)}${kv('Source',x.source_ref)}</article>`).join('')||empty('historical founder observations')}</section>`;}
function render(i){const p=$('#panel');if(!chart)return;
 if(i===0)p.innerHTML=`<div class=grid><div class=card><h3>BMR</h3><p>${esc(chart.identity.bmr.bmr_id)}</p><p>${esc(chart.identity.bmr.lifecycle_status)} · v${esc(chart.identity.bmr.record_version)}</p></div><div class=card><h3>Venture</h3><p>${esc(chart.identity.venture.venture_name)}</p></div></div>${renderHistoricalContext()}${chart.active_care_error?`<div class=card><strong>Active-care projection:</strong> ${esc(chart.active_care_error.message)}</div>`:''}`;
 else if(i===1)p.innerHTML=renderTimeline();
 else if(i===2)p.innerHTML=renderEvidence();
 else if(i===3)p.innerHTML=renderReasoning()+(window.operator.role==='business_physician'?governanceForm():'');
 else if(i===4)p.innerHTML=renderCare()+careForms();
 else if(i===5)p.innerHTML=noteForm()+activeCareEncounterForms();
 else p.innerHTML=outcomeForms();
 bindActions();
}
const form=(id,title,fields)=>`<form class=action id="${id}"><h3>${title}</h3>${fields}<button>Save</button><p class=msg></p></form>`;
const field=(n,l,tag='input',required=true)=>`<label>${l}<${tag} name="${n}" ${required?'required':''}></${tag}></label>`;
function noteForm(){return form('note','GalviClinic Note',field('value_text','Clinical note','textarea'))}
function governanceForm(){
  const findings=arr(chart?.reasoning?.findings);if(!findings.length)return `<section class="card"><h3>Finding Governance</h3>${empty('eligible findings')}</section>`;
  const options=findings.map(x=>{const id=first(x,['finding_id','id'],'');const gv=first(x,['governance_version'],'');const statement=first(x,['statement','title'],id);return `<option value="${esc(id)}" data-version="${esc(gv)}">${esc(statement)} — ${esc(first(x,['confirmation_status','status']))} — gv${esc(gv)}</option>`}).join('');
  return form('gov','Business Physician Finding Decision',`<label>Finding<select name="finding_id" required>${options}</select></label><label>Decision<select name="decision" required><option value="">Choose</option><option value="confirm">Confirm</option><option value="reject">Reject</option><option value="modify">Modify</option></select></label>${field('rationale','Clinical rationale','textarea')}${field('modified_statement','Modified finding statement (required only for Modify)','textarea',false)}`);
}
function treatmentForm(){
  const a=chart?.active_care||{},confirmed=arr(chart?.reasoning?.findings).filter(x=>String(first(x,['confirmation_status'],'')).toLowerCase()==='confirmed'),recs=arr(chart?.care?.recommendations).filter(x=>['proposed','approved'].includes(String(first(x,['status'],'')).toLowerCase()));
  if(window.operator.role!=='business_physician')return `<section class="card"><h3>Treatment authority</h3><p>Only a Business Physician may approve or revise an active Treatment Plan.</p></section>`;
  if(!a.brief_fingerprint||!confirmed.length||!recs.length)return `<section class="card"><h3>Treatment Plan</h3><p>A current Clinic brief, confirmed finding, and governed recommendation are required before treatment approval.</p></section>`;
  const fopts=confirmed.map(x=>`<option value="${esc(first(x,['finding_id','id'],''))}">${esc(first(x,['statement','title','finding_id']))}</option>`).join(''),ropts=recs.map(x=>`<option value="${esc(first(x,['recommendation_id','id'],''))}">${esc(first(x,['title','recommendation_text','recommendation_id']))}</option>`).join('');
  return form('plan','Business Physician Treatment Plan',`<label>Recommendation<select name="recommendation_id" required>${ropts}</select></label><label>Confirmed finding<select name="finding_id" required>${fopts}</select></label>${field('title','Plan title')}${field('clinical_priority','Clinical priority','textarea')}${field('objective','Measurable objective','textarea')}${field('action_title','Action')}${field('action_description','Action description','textarea')}${field('owner','Owner')}${field('evidence_required','Required evidence','textarea')}${field('target_metric','Target metric')}${field('milestone','Milestone')}${field('cadence','Monitoring cadence')}${field('escalation','Escalation trigger','textarea')}<label>Follow-up<input name="follow_up_at" type="datetime-local"></label>`);
}
function careForms(){
  const confirmed=arr(chart?.reasoning?.findings).filter(x=>String(first(x,['confirmation_status'],'')).toLowerCase()==='confirmed');
  const findingOptions=confirmed.map(x=>`<option value="${esc(first(x,['finding_id','id'],''))}">${esc(first(x,['statement','title','finding_id']))} — confirmed</option>`).join('');
  const recommendationForm=window.operator.role==='business_physician'&&confirmed.length?form('rec','Recommendation',`<label>Confirmed finding<select name="finding_id" required>${findingOptions}</select></label>${field('title','Title')}${field('action','Action','textarea')}${field('rationale','Rationale','textarea')}<label>Priority<input name="priority" type="number" min="0" step="1" value="1" required></label>`):'';
  const eventPlans=arr(chart?.active_care?.treatment_plans).length?arr(chart.active_care.treatment_plans):arr(chart?.care?.treatment_plans);
  const eventPlanOptions=eventPlans.map(x=>`<option value="${esc(first(x,['treatment_plan_id','id'],''))}">${esc(first(x,['title','name','treatment_plan_id']))} — ${esc(first(x,['status']))}</option>`).join('');
  const treatmentEventForm=eventPlans.length?form('treatment_event','Treatment Event',`<label>Treatment plan<select name="treatment_plan_id" required>${eventPlanOptions}</select>${field('event_type','Event type')}<label>Occurred at<input name="occurred_at" type="datetime-local" required></label>${field('notes','Notes','textarea')}`):'';
  return recommendationForm+treatmentForm()+treatmentEventForm;
}
function activeCareEncounterForms(){
  if(window.operator.role!=='business_physician')return '';
  const a=chart?.active_care||{},plans=arr(a.treatment_plans),findings=arr(chart?.reasoning?.findings);if(!plans.length)return `<section class="card"><h3>Active Care Orders</h3><p>Create an approved Treatment Plan first.</p></section>`;
  const popts=plans.map(x=>`<option value="${esc(first(x,['treatment_plan_id','id'],''))}">${esc(first(x,['name','title','treatment_plan_id']))}</option>`).join(''),fopts=findings.map(x=>`<option value="${esc(first(x,['finding_id','id'],''))}">${esc(first(x,['statement','title','finding_id']))}</option>`).join('');
  return form('rx','GalviRx',`<label>Treatment plan<select name="treatment_plan_id" required>${popts}</select></label>${field('intervention_code','Intervention code')}${field('resource_type','Resource type')}${field('resource_ref','Resource reference', 'input', false)}${field('instructions','Instructions','textarea')}${field('owner','Owner')}${field('expected_evidence','Expected evidence','textarea')}${field('cadence','Cadence')}${field('guardrails','Guardrails','textarea')}`)+
    form('audit_order','GalviAudit Order',`<label>Treatment plan<select name="treatment_plan_id" required>${popts}</select></label><label>Finding<select name="finding_id" required>${fopts}</select></label>${field('domain','Diagnostic domain')}${field('reason','Reason / question','textarea')}${field('evidence_requested','Evidence requested','textarea')}`)+
    form('referral','Qualified Referral',`<label>Treatment plan<select name="treatment_plan_id" required>${popts}</select></label><label>Finding<select name="finding_id" required>${fopts}</select></label>${field('category','Referral category')}${field('reason','Reason','textarea')}${field('provider_name','Provider name')}<label>Provider verification<select name="provider_verification_status" required><option value="verified">Verified</option><option value="unverified">Unverified</option></select></label><label>Consent<select name="consent_status" required><option value="consented">Consented</option><option value="needs_consent">Needs consent</option><option value="declined">Declined</option></select></label>${field('consent_version','Consent version')}`)+
    form('reassess','Reassessment',`<label>Treatment plan<select name="treatment_plan_id" required>${popts}</select></label><label>Decision<select name="decision" required><option value="continue">Continue</option><option value="modify">Modify</option><option value="escalate">Escalate</option><option value="close">Close</option><option value="needs_evidence">Needs evidence</option><option value="human_review">Human review</option></select></label>${field('reason','Reason','textarea')}`);
}
function outcomeForms(){
  const a=chart?.active_care||{},plans=arr(a.treatment_plans).length?arr(a.treatment_plans):arr(chart?.care?.treatment_plans),planOptions=plans.map(x=>`<option value="${esc(first(x,['treatment_plan_id','id'],''))}">${esc(first(x,['title','name','treatment_plan_id']))} — ${esc(first(x,['status']))}</option>`).join('');
  const outcomeForm=plans.length?form('outcome','Outcome',`<label>BMR ID<input name="bmr_id" value="${esc(chart.identity.bmr.bmr_id)}" readonly required></label><label>Treatment plan<select name="treatment_plan_id" required>${planOptions}</select></label>${field('outcome_code','Outcome code')}${field('value_text','Observed value','textarea')}<label>Observed at<input name="observed_at" type="datetime-local" required></label>`):'';
  const auditOptions=arr(a.galviaudit_orders).filter(x=>String(first(x,['status'],'')).toLowerCase()!=='completed').map(x=>`<option value="${esc(first(x,['audit_order_id','id'],''))}">${esc(first(x,['domain','audit_order_id']))}</option>`).join('');
  const referralOptions=arr(a.referrals).filter(x=>String(first(x,['consent_status'],'')).toLowerCase()==='consented'&&String(first(x,['status'],'')).toLowerCase()!=='completed').map(x=>`<option value="${esc(first(x,['referral_id','id'],''))}">${esc(first(x,['provider_name','category','referral_id']))}</option>`).join('');
  return outcomeForm+(auditOptions?form('audit_result','GalviAudit Result',`<label>Audit order<select name="audit_order_id" required>${auditOptions}</select></label>${field('result_summary','Governed result summary','textarea')}${field('source_ref','Source reference')}`):'')+(referralOptions?form('referral_outcome','Referral Outcome',`<label>Referral<select name="referral_id" required>${referralOptions}</select></label>${field('outcome_summary','Returned outcome','textarea')}${field('source_ref','Source reference')}`):'')+form('feedback','Feedback / Follow-up',field('target_type','Target type')+field('target_id','Target ID')+field('feedback_type','Feedback type')+field('comment','Comment','textarea'));
}
const key=(name,payload)=>{const raw=JSON.stringify(payload);const prev=retry.get(name);if(prev?.raw===raw)return prev.key;const k=`d8_${crypto.randomUUID().replaceAll('-','')}`;retry.set(name,{raw,key:k});return k};
async function postForm(f,path,payload){const name=f.id;f.querySelector('button').disabled=true;try{await api(path,{method:'POST',headers:{'Idempotency-Key':key(name,payload)},body:JSON.stringify(payload)});retry.delete(name);await openChart(selected);return true}catch(e){f.querySelector('.msg').textContent=e.status===409?'Record changed or source evidence advanced. Canonical chart refreshed; review before retry.':e.message;if(e.status===409)await openChart(selected);if(e.status===401)await load();return false}finally{f.querySelector('button').disabled=false}}
function bindActions(){
 const note=$('#note');if(note)note.onsubmit=e=>{e.preventDefault();const v=vals(note);postForm(note,'/api/v1/evidence',{bmr_id:selected,session_id:chart.identity.bmr.current_session_id,source_type:'facilitator_capture',source_ref:`galviclinic_note_${Date.now()}`,value_type:'text',value_text:v.value_text,captured_at:new Date().toISOString(),consent_status:'confirmed'})};
 const gov=$('#gov');if(gov)gov.onsubmit=e=>{e.preventDefault();const v=vals(gov);postForm(gov,'/api/v1/finding-decisions',{bmr_id:selected,finding_id:v.finding_id,decision:v.decision,rationale:v.rationale,modified_statement:v.decision==='modify'?v.modified_statement:undefined,encounter_fingerprint:chart.active_care?.brief_fingerprint,evidence_refs:[]})};
 const rec=$('#rec');if(rec)rec.onsubmit=e=>{e.preventDefault();const v=vals(rec);postForm(rec,'/api/v1/recommendations',{bmr_id:selected,finding_ids:[v.finding_id],recommendation_code:'GALVICLINIC_DAY5',title:v.title,action:v.action,rationale:v.rationale,priority:Number(v.priority),status:'proposed',source_type:'clinician',source_version:'day5'})};
 const plan=$('#plan');if(plan)plan.onsubmit=e=>{e.preventDefault();const v=vals(plan),a=chart.active_care||{};postForm(plan,'/api/v1/treatment-plans',{bmr_id:selected,recommendation_ids:[v.recommendation_id],finding_ids:[v.finding_id],treatment_code:'GALVICLINIC_PLAN',title:v.title,clinical_priority:v.clinical_priority,objective:v.objective,brief_fingerprint:a.brief_fingerprint,source_versions:a.source_versions,actions:[{title:v.action_title,description:v.action_description,owner:v.owner,evidence_required:v.evidence_required}],target_metrics:[{metric:v.target_metric,target:'improve'}],milestones:[{milestone:v.milestone,status:'planned'}],monitoring_plan:{cadence:v.cadence},escalation_triggers:[v.escalation],follow_up_at:v.follow_up_at?new Date(v.follow_up_at).toISOString():null})};
 const tev=$('#treatment_event');if(tev)tev.onsubmit=e=>{e.preventDefault();const v=vals(tev);postForm(tev,`/api/v1/treatment-plans/${encodeURIComponent(v.treatment_plan_id)}/events`,{event_type:v.event_type,occurred_at:new Date(v.occurred_at).toISOString(),notes:v.notes,metadata:{source:'galviclinic_day5'}})};
 const rx=$('#rx');if(rx)rx.onsubmit=e=>{e.preventDefault();const v=vals(rx);postForm(rx,'/api/v1/galvirx',{bmr_id:selected,treatment_plan_id:v.treatment_plan_id,intervention_code:v.intervention_code,resource_type:v.resource_type,resource_ref:v.resource_ref||null,instructions:v.instructions,owner:v.owner,expected_evidence:v.expected_evidence,cadence:v.cadence,guardrails:v.guardrails})};
 const ao=$('#audit_order');if(ao)ao.onsubmit=e=>{e.preventDefault();const v=vals(ao);postForm(ao,'/api/v1/galviaudit-orders',{bmr_id:selected,treatment_plan_id:v.treatment_plan_id,finding_id:v.finding_id,domain:v.domain,reason:v.reason,evidence_requested:[v.evidence_requested],assigned_service:'GalviLab'})};
 const ref=$('#referral');if(ref)ref.onsubmit=e=>{e.preventDefault();const v=vals(ref);postForm(ref,'/api/v1/referrals',{bmr_id:selected,treatment_plan_id:v.treatment_plan_id,finding_id:v.finding_id,category:v.category,reason:v.reason,provider_name:v.provider_name,provider_verification_status:v.provider_verification_status,consent_status:v.consent_status,consent_version:v.consent_version,minimum_disclosure:{bmr_id:selected,purpose:'specialty_referral'}})};
 const reassess=$('#reassess');if(reassess)reassess.onsubmit=e=>{e.preventDefault();const v=vals(reassess);postForm(reassess,'/api/v1/reassessments',{bmr_id:selected,treatment_plan_id:v.treatment_plan_id,decision:v.decision,reason:v.reason,evidence_refs:[],outcome_refs:[],source_versions:chart.active_care?.source_versions||{}})};
 const out=$('#outcome');if(out)out.onsubmit=e=>{e.preventDefault();const v=vals(out);postForm(out,'/api/v1/outcomes',{bmr_id:selected,treatment_plan_id:v.treatment_plan_id,outcome_code:v.outcome_code,outcome_type:'observed',value_text:v.value_text,observed_at:new Date(v.observed_at).toISOString(),source_type:'clinician',source_ref:'galviclinic_day5',status:'observed'})};
 const ar=$('#audit_result');if(ar)ar.onsubmit=e=>{e.preventDefault();const v=vals(ar);postForm(ar,`/api/v1/galviaudit-orders/${encodeURIComponent(v.audit_order_id)}/result`,{bmr_id:selected,result_summary:v.result_summary,source_ref:v.source_ref,source_type:'galviaudit_result'})};
 const ro=$('#referral_outcome');if(ro)ro.onsubmit=e=>{e.preventDefault();const v=vals(ro);postForm(ro,`/api/v1/referrals/${encodeURIComponent(v.referral_id)}/outcome`,{bmr_id:selected,outcome_summary:v.outcome_summary,source_ref:v.source_ref,source_type:'referral_outcome'})};
 const fb=$('#feedback');if(fb)fb.onsubmit=e=>{e.preventDefault();const v=vals(fb);postForm(fb,'/api/v1/feedback',{...v,bmr_id:selected,disposition:'follow_up',source:'clinician'})};
}
$('#logout').addEventListener('click',async()=>{try{await api('/api/v1/operator/auth/logout',{method:'POST',body:'{}'})}finally{showAuth('Signed out securely.');}});load();